package net.integrategroup.ignite.persistence.repository;

import java.util.List;

import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.CrudRepository;
import org.springframework.stereotype.Repository;

import net.integrategroup.ignite.persistence.model.IndividualQualification;
import net.integrategroup.ignite.persistence.model.VIndividualQualification;


/** @author Generated by Johannes Marais (JohannesSQL v7.7) **/
/** ******* ********* ** 2023-10-16 19:51:56 ******** ***** **/

@Repository
public interface IndividualQualificationRepository extends CrudRepository<IndividualQualification, Long> {

	@Override
	List<IndividualQualification> findAll();

	@Query("Select i   FROM  IndividualQualification i    WHERE  i.individualQualificationId = ?1")
	IndividualQualification getByIndividualQualificationId(Long individualQualificationId);


//	@Query("Select v   FROM  VIndividualQualification v   WHERE  v.individualQualificationId = ?1")       //One record from View
//	VIndividualQualification getByVIndividualQualificationId(Long individualQualificationId);





//	@Query("SELECT v FROM VIndividualQualification v")									//All in view
//	List<VIndividualQualification> findListAllInView();

//	@Query("SELECT v FROM VIndividualQualification v WHERE v.columnName = 'XXX'")		//List from View without parameter
//	List<VIndividualQualification> findListVIndividualQualificationXXX();

	@Query("SELECT v FROM VIndividualQualification v WHERE v.participantId = ?1")				//List from View that needs parameter
	List<VIndividualQualification> findListVIndividualQualificationForParticipant(Long participantId);

//	@Query("SELECT v FROM VIndividualQualification v WHERE v.columnName = ?1 AND v.columnName = ?2 and v.columnName = ?3")	//List from View that needs multiple parameters
//	List<VIndividualQualification> findListVIndividualQualificationXXX(Long paramId, String paramName, String paramName2);

//	@Query("SELECT v FROM VIndividualQualification v "									//List from View that needs date parameters
//		" WHERE    v.paramId = ?1 "
//		" AND      v.paramDate  BETWEEN ?2 AND ?3 "
//		" ORDER BY v.paramDate ")
//	List<VIndividualQualification> findListVIndividualQualificationXXX(Long paramId, Date fd, Date ld);




	@Query("Select i   FROM  IndividualQualification i    WHERE  i.individualId = ?1")
	List<IndividualQualification> findListIndividualQualificationForIndividualId(Long individualId);

	@Query("Select i   FROM  IndividualQualification i    WHERE  i.instituteQualificationId = ?1")
	List<IndividualQualification> findListIndividualQualificationForInstituteQualificationId(Long instituteQualificationId);


}