package net.integrategroup.ignite.persistence.repository;

import java.util.List;

import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.CrudRepository;
import org.springframework.stereotype.Repository;

import net.integrategroup.ignite.persistence.model.StudyInstitute;


/** @author Generated by Johannes Marais (JohannesSQL v7.7) **/
/** ******* ********* ** 2023-10-16 19:51:59 ******** ***** **/

@Repository
public interface StudyInstituteRepository extends CrudRepository<StudyInstitute, Long> {

	@Override
	List<StudyInstitute> findAll();

	@Query("Select i   FROM  StudyInstitute i    WHERE  i.studyInstituteId = ?1")
	StudyInstitute getByStudyInstituteId(Long studyInstituteId);


//	@Query("Select v   FROM  VStudyInstitute v   WHERE  v.studyInstituteId = ?1")       //One record from View
//	VStudyInstitute getByVStudyInstituteId(Long studyInstituteId);



}