package net.integrategroup.ignite.persistence.repository;

import java.util.List;

import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.CrudRepository;
import org.springframework.stereotype.Repository;

import net.integrategroup.ignite.persistence.model.Suburb;
import net.integrategroup.ignite.persistence.model.VSuburb;
import net.integrategroup.ignite.persistence.model.VSuburbMin;


/** @author Generated by Johannes Marais (JohannesSQL v7.7) **/
/** ******* ********* ** 2023-10-10 10:46:17 ******** ***** **/

@Repository
public interface SuburbRepository extends CrudRepository<Suburb, Long> {

	@Override
	List<Suburb> findAll();

	@Query("Select i   FROM  Suburb i    WHERE  i.suburbId = ?1")
	Suburb getBySuburbId(Long suburbId);


//	@Query("Select v   FROM  VSuburb v   WHERE  v.suburbId = ?1")       //One record from View
//	VSuburb getByVSuburbId(Long suburbId);





	@Query("SELECT v FROM VSuburb v")									//All in view
	List<VSuburb> findListAllInView();

//	@Query("SELECT v FROM VSuburb v WHERE v.columnName = 'XXX'")		//List from View without parameter
//	List<VSuburb> findListVSuburbXXX();

	@Query("SELECT v FROM VSuburbMin v WHERE v.cityId = ?1")				//List from Min View that needs parameter
	List<VSuburbMin> findListVSuburbMinForCity(Long cityId);

//	@Query("SELECT v FROM VSuburb v WHERE v.columnName = ?1 AND v.columnName = ?2 and v.columnName = ?3")	//List from View that needs multiple parameters
//	List<VSuburb> findListVSuburbXXX(Long paramId, String paramName, String paramName2);

//	@Query("SELECT v FROM VSuburb v "									//List from View that needs date parameters
//		" WHERE    v.paramId = ?1 "
//		" AND      v.paramDate  BETWEEN ?2 AND ?3 "
//		" ORDER BY v.paramDate ")
//	List<VSuburb> findListVSuburbXXX(Long paramId, Date fd, Date ld);




	@Query("Select i   FROM  VSuburb i    WHERE  i.cityId = ?1")
	List<VSuburb> findListSuburbForCityId(Long cityId);


}