/*
-- Query: SELECT * FROM ig_db.UiComponent
LIMIT 0, 1000

-- Date: 2021-07-02 13:50
*/
INSERT INTO `ig_db`.`UiComponent` (`UiComponentId`,`UiComponentTitle`,`UiComponentLink`,`OrderNo`,`ParentUiComponentId`,`ActiveInd`,`RequiredPermissionCode`,`IconClassName`,`LastUpdateTimestamp`,`LastUpdateUserName`) VALUES (10,'Individuals','/individual',10,NULL,'Y','menu-individual-view','fas fa-user','2021-03-18 12:50:17','admin');
INSERT INTO `ig_db`.`UiComponent` (`UiComponentId`,`UiComponentTitle`,`UiComponentLink`,`OrderNo`,`ParentUiComponentId`,`ActiveInd`,`RequiredPermissionCode`,`IconClassName`,`LastUpdateTimestamp`,`LastUpdateUserName`) VALUES (20,'Participants','/participant',20,NULL,'Y','menu-participants-view','fas fa-users','2021-03-18 12:50:17','admin');
INSERT INTO `ig_db`.`UiComponent` (`UiComponentId`,`UiComponentTitle`,`UiComponentLink`,`OrderNo`,`ParentUiComponentId`,`ActiveInd`,`RequiredPermissionCode`,`IconClassName`,`LastUpdateTimestamp`,`LastUpdateUserName`) VALUES (30,'Projects','/project',30,NULL,'Y','menu-projects-view','fas fa-project-diagram','2021-03-18 12:50:17','admin');
INSERT INTO `ig_db`.`UiComponent` (`UiComponentId`,`UiComponentTitle`,`UiComponentLink`,`OrderNo`,`ParentUiComponentId`,`ActiveInd`,`RequiredPermissionCode`,`IconClassName`,`LastUpdateTimestamp`,`LastUpdateUserName`) VALUES (35,'Reports','/report',35,NULL,'Y','menu-reports-view','fas fa-book','2021-03-19 13:01:28','admin');
INSERT INTO `ig_db`.`UiComponent` (`UiComponentId`,`UiComponentTitle`,`UiComponentLink`,`OrderNo`,`ParentUiComponentId`,`ActiveInd`,`RequiredPermissionCode`,`IconClassName`,`LastUpdateTimestamp`,`LastUpdateUserName`) VALUES (40,'Setup',NULL,50,NULL,'Y','menu-setup-view','fas fa-cog','2021-03-18 12:50:17','admin');
INSERT INTO `ig_db`.`UiComponent` (`UiComponentId`,`UiComponentTitle`,`UiComponentLink`,`OrderNo`,`ParentUiComponentId`,`ActiveInd`,`RequiredPermissionCode`,`IconClassName`,`LastUpdateTimestamp`,`LastUpdateUserName`) VALUES (50,'General','/setup-general',10,40,'Y','menu-setup-general-view',NULL,'2021-03-18 12:50:17','admin');
INSERT INTO `ig_db`.`UiComponent` (`UiComponentId`,`UiComponentTitle`,`UiComponentLink`,`OrderNo`,`ParentUiComponentId`,`ActiveInd`,`RequiredPermissionCode`,`IconClassName`,`LastUpdateTimestamp`,`LastUpdateUserName`) VALUES (60,'APIs','/setup-api',20,40,'Y','menu-setup-apis-view',NULL,'2021-03-18 12:50:17','admin');
INSERT INTO `ig_db`.`UiComponent` (`UiComponentId`,`UiComponentTitle`,`UiComponentLink`,`OrderNo`,`ParentUiComponentId`,`ActiveInd`,`RequiredPermissionCode`,`IconClassName`,`LastUpdateTimestamp`,`LastUpdateUserName`) VALUES (70,'Calendar','/setup-calendar',30,40,'Y','menu-setup-calendar-view',NULL,'2021-03-18 12:50:17','admin');
INSERT INTO `ig_db`.`UiComponent` (`UiComponentId`,`UiComponentTitle`,`UiComponentLink`,`OrderNo`,`ParentUiComponentId`,`ActiveInd`,`RequiredPermissionCode`,`IconClassName`,`LastUpdateTimestamp`,`LastUpdateUserName`) VALUES (80,'Reference Data',NULL,40,40,'Y','menu-setup-reference-data-view',NULL,'2021-03-18 12:50:17','admin');
INSERT INTO `ig_db`.`UiComponent` (`UiComponentId`,`UiComponentTitle`,`UiComponentLink`,`OrderNo`,`ParentUiComponentId`,`ActiveInd`,`RequiredPermissionCode`,`IconClassName`,`LastUpdateTimestamp`,`LastUpdateUserName`) VALUES (85,'Reports','/setup-report',50,40,'Y','menu-setup-reports-view',NULL,'2021-03-23 08:30:26','admin');
INSERT INTO `ig_db`.`UiComponent` (`UiComponentId`,`UiComponentTitle`,`UiComponentLink`,`OrderNo`,`ParentUiComponentId`,`ActiveInd`,`RequiredPermissionCode`,`IconClassName`,`LastUpdateTimestamp`,`LastUpdateUserName`) VALUES (88,'Bank Account Types','/setup-bank-account-type',5,80,'Y','menu-setup-bank-account-type-view',NULL,'2021-03-31 12:11:27','admin');
INSERT INTO `ig_db`.`UiComponent` (`UiComponentId`,`UiComponentTitle`,`UiComponentLink`,`OrderNo`,`ParentUiComponentId`,`ActiveInd`,`RequiredPermissionCode`,`IconClassName`,`LastUpdateTimestamp`,`LastUpdateUserName`) VALUES (90,'Banks & Branches','/setup-bank',10,80,'Y','menu-setup-banks-&-branches-view',NULL,'2021-03-18 12:50:17','admin');
INSERT INTO `ig_db`.`UiComponent` (`UiComponentId`,`UiComponentTitle`,`UiComponentLink`,`OrderNo`,`ParentUiComponentId`,`ActiveInd`,`RequiredPermissionCode`,`IconClassName`,`LastUpdateTimestamp`,`LastUpdateUserName`) VALUES (95,'Countries','/setup-country',15,80,'Y','menu-setup-countries-view',NULL,'2021-03-30 15:55:27','admin');
INSERT INTO `ig_db`.`UiComponent` (`UiComponentId`,`UiComponentTitle`,`UiComponentLink`,`OrderNo`,`ParentUiComponentId`,`ActiveInd`,`RequiredPermissionCode`,`IconClassName`,`LastUpdateTimestamp`,`LastUpdateUserName`) VALUES (100,'Operational Services','/setup-operational-service-discipline',20,80,'Y','menu-setup-operational-services-discipline-view',NULL,'2021-03-18 12:50:17','admin');
INSERT INTO `ig_db`.`UiComponent` (`UiComponentId`,`UiComponentTitle`,`UiComponentLink`,`OrderNo`,`ParentUiComponentId`,`ActiveInd`,`RequiredPermissionCode`,`IconClassName`,`LastUpdateTimestamp`,`LastUpdateUserName`) VALUES (110,'Participation Types','/setup-participation-type',30,80,'Y','menu-setup-participation-type-view',NULL,'2021-03-18 12:50:17','admin');
INSERT INTO `ig_db`.`UiComponent` (`UiComponentId`,`UiComponentTitle`,`UiComponentLink`,`OrderNo`,`ParentUiComponentId`,`ActiveInd`,`RequiredPermissionCode`,`IconClassName`,`LastUpdateTimestamp`,`LastUpdateUserName`) VALUES (120,'Participant Status','/setup-participant-status',40,80,'Y','menu-setup-participant-status-view',NULL,'2021-03-18 12:50:17','admin');
INSERT INTO `ig_db`.`UiComponent` (`UiComponentId`,`UiComponentTitle`,`UiComponentLink`,`OrderNo`,`ParentUiComponentId`,`ActiveInd`,`RequiredPermissionCode`,`IconClassName`,`LastUpdateTimestamp`,`LastUpdateUserName`) VALUES (130,'Resource Status','/setup-resource-status',50,80,'Y','menu-setup-resource-status-view',NULL,'2021-03-18 12:50:17','admin');
INSERT INTO `ig_db`.`UiComponent` (`UiComponentId`,`UiComponentTitle`,`UiComponentLink`,`OrderNo`,`ParentUiComponentId`,`ActiveInd`,`RequiredPermissionCode`,`IconClassName`,`LastUpdateTimestamp`,`LastUpdateUserName`) VALUES (140,'Roles & Permissions','/setup-role',50,40,'Y','menu-setup-roles-&-permissions-view',NULL,'2021-03-18 12:50:17','admin');
INSERT INTO `ig_db`.`UiComponent` (`UiComponentId`,`UiComponentTitle`,`UiComponentLink`,`OrderNo`,`ParentUiComponentId`,`ActiveInd`,`RequiredPermissionCode`,`IconClassName`,`LastUpdateTimestamp`,`LastUpdateUserName`) VALUES (150,'Timesheet','/timesheet',40,NULL,'Y','menu-timesheet-view','fas fa-clock','2021-03-18 12:50:17','admin');
INSERT INTO `ig_db`.`UiComponent` (`UiComponentId`,`UiComponentTitle`,`UiComponentLink`,`OrderNo`,`ParentUiComponentId`,`ActiveInd`,`RequiredPermissionCode`,`IconClassName`,`LastUpdateTimestamp`,`LastUpdateUserName`) VALUES (160,'About','/about',60,NULL,'Y','menu-about-view','fas fa-info-circle','2021-03-18 12:50:17','admin');
INSERT INTO `ig_db`.`UiComponent` (`UiComponentId`,`UiComponentTitle`,`UiComponentLink`,`OrderNo`,`ParentUiComponentId`,`ActiveInd`,`RequiredPermissionCode`,`IconClassName`,`LastUpdateTimestamp`,`LastUpdateUserName`) VALUES (161,'Support Services','/setup-support-service',60,40,'Y','menu-setup-support-service-view',NULL,'2021-04-20 12:03:35','admin');
