package net.integrategroup.ignite.persistence.model;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import com.fasterxml.jackson.databind.annotation.JsonSerialize;

import net.integrategroup.ignite.utils.JsonDateSerializer;

/** @author Generated by Johannes Marais (JohannesSQL v4.8) **/
/** ******* ********* ** 2023-06-19 08:10:54 ******** ***** **/

@Entity
@Table(schema = "ig_db", name = "BankTransactionLink")
public class BankTransactionLink implements Serializable {


    /**
	 *
	 */
	private static final long serialVersionUID = 7074607343174379646L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "BankTransactionLinkId")
	private Long bankTransactionLinkId;

	@Column(name = "BankTransactionId")
	private Long bankTransactionId;

/***	@OneToOne(targetEntity = BankTransaction.class)
	@JoinColumn(name = "BankTransactionId", referencedColumnName = "BankTransactionId", nullable = true, insertable = false, updatable = false)
	private BankTransaction bankTransaction; ***/

	@Column(name = "InvoiceId")
	private Long invoiceId;

/***	@OneToOne(targetEntity = Invoice.class)
	@JoinColumn(name = "InvoiceId", referencedColumnName = "InvoiceId", nullable = true, insertable = false, updatable = false)
	private Invoice invoice; ***/

	@Column(name = "ProjectExpenseId")
	private Long projectExpenseId;

/***	@OneToOne(targetEntity = ProjectExpense.class)
	@JoinColumn(name = "ProjectExpenseId", referencedColumnName = "ProjectExpenseId", nullable = true, insertable = false, updatable = false)
	private ProjectExpense projectExpense; ***/

	@Column(name = "ParticipantIdApprovedLink")
	private Long participantIdApprovedLink;

/***	@OneToOne(targetEntity = Participant.class)
	@JoinColumn(name = "ParticipantIdApprovedLink", referencedColumnName = "ParticipantId", nullable = true, insertable = false, updatable = false)
	private Participant participant; ***/

	@Column(name = "LinkAmount")
	private Double linkAmount;

	@JsonSerialize(using = JsonDateSerializer.class)
	@Column(name = "AutomaticCursorLinkCreated")
	private Date automaticCursorLinkCreated;

	@JsonSerialize(using = JsonDateSerializer.class)
	@Column(name = "LinkApproved")
	private Date linkApproved;

	@Column(name = "Description")
	private String description;

	@JsonSerialize(using = JsonDateSerializer.class)
	@Column(name = "LastUpdateTimestamp")
	private Date lastUpdateTimestamp;

	@Column(name = "LastUpdateUserName")
	private String lastUpdateUserName;




	public Long getBankTransactionLinkId() {
		return bankTransactionLinkId;
	}

	public void setBankTransactionLinkId(Long bankTransactionLinkId) {
		this.bankTransactionLinkId = bankTransactionLinkId;
	}

	public Long getBankTransactionId() {
		return bankTransactionId;
	}

	public void setBankTransactionId(Long bankTransactionId) {
		this.bankTransactionId = bankTransactionId;
	}

/***	public BankTransaction getBankTransaction() {
		return bankTransaction;
	}

	public void setBankTransaction(BankTransaction bankTransaction) {
		this.bankTransaction = bankTransaction;
	} ***/

	public Long getInvoiceId() {
		return invoiceId;
	}

	public void setInvoiceId(Long invoiceId) {
		this.invoiceId = invoiceId;
	}

/***	public Invoice getInvoice() {
		return invoice;
	}

	public void setInvoice(Invoice invoice) {
		this.invoice = invoice;
	} ***/

	public Long getProjectExpenseId() {
		return projectExpenseId;
	}

	public void setProjectExpenseId(Long projectExpenseId) {
		this.projectExpenseId = projectExpenseId;
	}

/***	public ProjectExpense getProjectExpense() {
		return projectExpense;
	}

	public void setProjectExpense(ProjectExpense projectExpense) {
		this.projectExpense = projectExpense;
	} ***/

	public Long getParticipantIdApprovedLink() {
		return participantIdApprovedLink;
	}

	public void setParticipantIdApprovedLink(Long participantIdApprovedLink) {
		this.participantIdApprovedLink = participantIdApprovedLink;
	}

/***	public Participant getParticipant() {
		return participant;
	}

	public void setParticipant(Participant participant) {
		this.participant = participant;
	} ***/

	public Double getLinkAmount() {
		return linkAmount;
	}

	public void setLinkAmount(Double linkAmount) {
		this.linkAmount = linkAmount;
	}

	public Date getAutomaticCursorLinkCreated() {
		return automaticCursorLinkCreated;
	}

	public void setAutomaticCursorLinkCreated(Date automaticCursorLinkCreated) {
		this.automaticCursorLinkCreated = automaticCursorLinkCreated;
	}

	public Date getLinkApproved() {
		return linkApproved;
	}

	public void setLinkApproved(Date linkApproved) {
		this.linkApproved = linkApproved;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Date getLastUpdateTimestamp() {
		return lastUpdateTimestamp;
	}

	public void setLastUpdateTimestamp(Date lastUpdateTimestamp) {
		this.lastUpdateTimestamp = lastUpdateTimestamp;
	}

	public String getLastUpdateUserName() {
		return lastUpdateUserName;
	}

	public void setLastUpdateUserName(String lastUpdateUserName) {
		this.lastUpdateUserName = lastUpdateUserName;
	}


}

/**  javascript
		{ data: "bankTransactionLinkId" },    //0 MySql-TableName: BankTransactionLink
		{ data: "bankTransactionId" },        //1
		{ data: "invoiceId" },                //2
		{ data: "projectExpenseId" },         //3
		{ data: "participantIdApprovedLink" }, //4
		{ data: "linkAmount" },               //5
		{ data: "automaticCursorLinkCreated" }, //6
		{ data: "linkApproved" },             //7
		{ data: "description" },              //8
		{ data: "lastUpdateTimestamp" },      //9
		{ data: "lastUpdateUserName" },       //10

/**  html
										<th>BankTransactionLinkId</th>    <!--0  MySql-TableName: BankTransactionLink-->
										<th>BankTransactionId</th>        <!--1  BankTransactionId-->
										<th>InvoiceId</th>                <!--2  InvoiceId-->
										<th>ProjectExpenseId</th>         <!--3  ProjectExpenseId-->
										<th>ParticipantIdApprovedLink</th> <!--4  ParticipantIdApprovedLink-->
										<th>LinkAmount</th>               <!--5  LinkAmount-->
										<th>AutomaticCursorLinkCreated</th> <!--6  AutomaticCursorLinkCreated-->
										<th>LinkApproved</th>             <!--7  LinkApproved-->
										<th>Description</th>              <!--8  Description-->
										<th>LastUpdateTimestamp</th>      <!--9  LastUpdateTimestamp-->
										<th>LastUpdateUserName</th>       <!--10  LastUpdateUserName-->

*/