package net.integrategroup.ignite.persistence.model;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import com.fasterxml.jackson.databind.annotation.JsonSerialize;

import net.integrategroup.ignite.utils.JsonDateSerializer;

/** @author Generated by Johannes Marais (JohannesSQL v7.7) **/
/** ******* ********* ** 2023-10-16 19:51:56 ******** ** **/

@Entity
@Table(schema = "ig_db", name = "InstituteQualification")
public class InstituteQualification implements Serializable {


    private static final long serialVersionUID = 993293976077763644L; /** ID was Generated by Johannes **/


    @Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "InstituteQualificationId")
	private Long instituteQualificationId;

	@Column(name = "StudyInstituteId")
	private Long studyInstituteId;

/***	@OneToOne(targetEntity = StudyInstitute.class)
	@JoinColumn(name = "StudyInstituteId", referencedColumnName = "StudyInstituteId", nullable = true, insertable = false, updatable = false)
	private StudyInstitute studyInstitute; ***/

	@Column(name = "Name")
	private String name;

	@Column(name = "Description")
	private String description;

	@JsonSerialize(using = JsonDateSerializer.class)
	@Column(name = "LastUpdateTimestamp")
	private Date lastUpdateTimestamp;

	@Column(name = "LastUpdateUserName")
	private String lastUpdateUserName;




	public Long getInstituteQualificationId() {
		return instituteQualificationId;
	}

	public void setInstituteQualificationId(Long instituteQualificationId) {
		this.instituteQualificationId = instituteQualificationId;
	}

	public Long getStudyInstituteId() {
		return studyInstituteId;
	}

	public void setStudyInstituteId(Long studyInstituteId) {
		this.studyInstituteId = studyInstituteId;
	}

/***	public StudyInstitute getStudyInstitute() {
		return studyInstitute;
	}

	public void setStudyInstitute(StudyInstitute studyInstitute) {
		this.studyInstitute = studyInstitute;
	} ***/

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Date getLastUpdateTimestamp() {
		return lastUpdateTimestamp;
	}

	public void setLastUpdateTimestamp(Date lastUpdateTimestamp) {
		this.lastUpdateTimestamp = lastUpdateTimestamp;
	}

	public String getLastUpdateUserName() {
		return lastUpdateUserName;
	}

	public void setLastUpdateUserName(String lastUpdateUserName) {
		this.lastUpdateUserName = lastUpdateUserName;
	}


}

/**  javascript      vir grid population        (jsStr)

	var columnsArray = [
		 { data: "instituteQualificationId" } //0 MySql-TableName: InstituteQualification
		,{ data: "studyInstituteId" }         //1
		,{ data: "name" }                     //2
		,{ data: "description" }              //3
		,{ data: "lastUpdateTimestamp" }      //4
		,{ data: "lastUpdateUserName" }       //5
	];

	var columnDefsArray = [
		{
			visible: false,
			targets: [0, 1, 5]
		}
		,{       //for Date columns
			render: function (data, type, row) {
				var html = data;
				if (type == "display") {
					html = timestampToString(data, false);
				}
				return html;
			},
			targets: [4]
		}
	];







/**  javascript      vir grid SelectFromGridDialog        (js1Str)

	var columns = [
		{ data: "instituteQualificationId", name: "InstituteQualificationId" } //0 MySql-TableName: InstituteQualification
		,{ data: "studyInstituteId", name: "StudyInstituteId" }             //1
		,{ data: "name", name: "Name" }                                     //2
		,{ data: "description", name: "Description" }                       //3
		,{ data: "lastUpdateTimestamp", name: "LastUpdateTimestamp" }       //4
		,{ data: "lastUpdateUserName", name: "LastUpdateUserName" }         //5
	];

	var columnDefs = [
		{
			visible: false,
			targets: [0, 1, 5]
		}
		,{       //for Date columns
			render: function (data, type, row) {
				var html = data;
				if (type == "display") {
					html = timestampToString(data, false);
				}
				return html;
			},
			targets: [4]
		}
	];







Vir 'n Save Data function                        (js2Str)


	var postUrl = "/rest/ignite/v1/institute-qualification/new";
	var postData = {
		instituteQualificationId : $("#InstituteQualificationId").val() //0 MySql-TableName: InstituteQualification
		,studyInstituteId : $("#StudyInstituteId").val()                          //1
		,name : $("#Name").val()                                                  //2
		,description : $("#Description").val()                                    //3
		,lastUpdateTimestamp : getMsFromDatePicker("LastUpdateTimestamp")         //4
	};

	var errors = "";






Vir 'n Populate Data function                                                  (js3Str)

		//  MySql-TableName: InstituteQualification										   (js3Str)
		$("#InstituteQualificationId").val(data.instituteQualificationId); //0
		$("#StudyInstituteId").val(data.studyInstituteId);             //1
		populateSelect("StudyInstituteId",                                //name of html select element that will be populated
				"/rest/ignite/v1/study-institute/find-all",               //url
				"studyInstituteId",                                       //the value that must be saved (ReferencedColumnName)
				"name",                                                   //shown to user (usually a Name column)
				data.studyInstituteId,                                    //The selected one, if there is one
				true,                                                     //addEmpty, boolean: should we add empty object at the top
				null                                                      //completeMethod
		),

		$("#Name").val(data.name);                                     //2
		$("#Description").val(data.description);                       //3
		$("#LastUpdateTimestamp").datepicker("setDate", data.lastUpdateTimestamp == null? timestampToString(new Date(), false) : new Date(data.lastUpdateTimestamp));       //4






/**  HTML  om 'n grid te populate
												<th>InstituteQualificationId</th>    <!--0  MySql-TableName: InstituteQualification-->
												<th>StudyInstituteId</th>            <!--1  StudyInstituteId-->
												<th>Name</th>                        <!--2  Name-->
												<th>Description</th>                 <!--3  Description-->
												<th>Last Update Timestamp</th>       <!--4  LastUpdateTimestamp-->
												<th>LastUpdateUserName</th>          <!--5  LastUpdateUserName-->

*/