package net.integrategroup.ignite.persistence.model;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import com.fasterxml.jackson.databind.annotation.JsonSerialize;

import net.integrategroup.ignite.utils.JsonDateSerializer;

/** @author Generated by Johannes Marais (JohannesSQL v7.5) **/
/** ******* ********* ** 2023-09-04 14:34:56 ******** ** **/
/** ******* ********* ** Ingrid made changes 2023-09-07 ******** ** **/


@Entity
@Table(schema = "ig_db", name = "Invoice")
public class Invoice implements Serializable {


    private static final long serialVersionUID = 341988012836804894L; /** ID was Generated by Johannes **/

    @Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "InvoiceId")
	private Long invoiceId;

	@Column(name = "ParticipantIdFrom")
	private Long participantIdFrom;

	@Column(name = "ParticipantIdTo")
	private Long participantIdTo;

	@Column(name = "FlagDraft")
	private String flagDraft;

	@JsonSerialize(using = JsonDateSerializer.class)
	@Column(name = "UpUntilGenerateDate")
	private Date upUntilGenerateDate;

	@Column(name = "InvoiceHeading")
	private String invoiceHeading;

	@JsonSerialize(using = JsonDateSerializer.class)
	@Column(name = "InvoiceDate")
	private Date invoiceDate;

	@Column(name = "InvoiceNumber")
	private String invoiceNumber;

	@Column(name = "InvoiceAmountExclTax")
	private Double invoiceAmountExclTax;

	@Column(name = "InvoiceTaxAmount")
	private Double invoiceTaxAmount;

	@Column(name = "InvoiceTotalAmountInclTax")
	private Double invoiceTotalAmountInclTax;


	@Column(name = "Description")
	private String description;

	@JsonSerialize(using = JsonDateSerializer.class)
	@Column(name = "DateSentOrReceived")
	private Date dateSentOrReceived;

	@Column(name = "FromParticipantName")
	private String fromParticipantName;

	@Column(name = "FromCompRegistrationNumber")
	private String fromCompRegistrationNumber;

	@Column(name = "FromAddress")
	private String fromAddress;

	@Column(name = "FromVatNumber")
	private String fromVatNumber;

	@Column(name = "FromEmailAddress")
	private String fromEmailAddress;

	@Column(name = "FromPhoneNumber")
	private String fromPhoneNumber;

	@Column(name = "FromBankDetails")
	private String fromBankDetails;

	@Column(name = "FromThankYouMsg")
	private String fromThankYouMsg;

	@Column(name = "ToParticipantName")
	private String toParticipantName;

	@Column(name = "ToCompRegistrationNumber")
	private String toCompRegistrationNumber;

	@Column(name = "ToAddress")
	private String toAddress;

	@Column(name = "ToVatNumber")
	private String toVatNumber;

	@Column(name = "ToEmailAddress")
	private String toEmailAddress;

	@Column(name = "ToPhoneNumber")
	private String toPhoneNumber;

	@Column(name = "ToAttention")
	private String toAttention;

	@Column(name = "RatesMissing")
	private Integer ratesMissing;
	
	@Column(name = "ClientReference")
	private String clientReference;

	@JsonSerialize(using = JsonDateSerializer.class)
	@Column(name = "LastUpdateTimestamp")
	private Date lastUpdateTimestamp;

	@Column(name = "LastUpdateUserName")
	private String lastUpdateUserName;



	public String getClientReference() {
		return clientReference;
	}

	public void setClientReference(String clientReference) {
		this.clientReference = clientReference;
	}

	public String getFromCompRegistrationNumber() {
		return fromCompRegistrationNumber;
	}

	public void setFromCompRegistrationNumber(String fromCompRegistrationNumber) {
		this.fromCompRegistrationNumber = fromCompRegistrationNumber;
	}

	public String getToCompRegistrationNumber() {
		return toCompRegistrationNumber;
	}

	public void setToCompRegistrationNumber(String toCompRegistrationNumber) {
		this.toCompRegistrationNumber = toCompRegistrationNumber;
	}

	public Integer getRatesMissing() {
		return ratesMissing;
	}

	public void setRatesMissing(Integer ratesMissing) {
		this.ratesMissing = ratesMissing;
	}

	public Long getInvoiceId() {
		return invoiceId;
	}

	public void setInvoiceId(Long invoiceId) {
		this.invoiceId = invoiceId;
	}

	public Long getParticipantIdFrom() {
		return participantIdFrom;
	}

	public void setParticipantIdFrom(Long participantIdFrom) {
		this.participantIdFrom = participantIdFrom;
	}

	public Long getParticipantIdTo() {
		return participantIdTo;
	}

	public void setParticipantIdTo(Long participantIdTo) {
		this.participantIdTo = participantIdTo;
	}

	public String getFlagDraft() {
		return flagDraft;
	}

	public void setFlagDraft(String flagDraft) {
		this.flagDraft = flagDraft;
	}

	public Date getUpUntilGenerateDate() {
		return upUntilGenerateDate;
	}

	public void setUpUntilGenerateDate(Date upUntilGenerateDate) {
		this.upUntilGenerateDate = upUntilGenerateDate;
	}

	public String getInvoiceHeading() {
		return invoiceHeading;
	}

	public void setInvoiceHeading(String invoiceHeading) {
		this.invoiceHeading = invoiceHeading;
	}

	public Date getInvoiceDate() {
		return invoiceDate;
	}

	public void setInvoiceDate(Date invoiceDate) {
		this.invoiceDate = invoiceDate;
	}

	public String getInvoiceNumber() {
		return invoiceNumber;
	}

	public void setInvoiceNumber(String invoiceNumber) {
		this.invoiceNumber = invoiceNumber;
	}

	public Double getInvoiceAmountExclTax() {
		return invoiceAmountExclTax;
	}

	public void setInvoiceAmountExclTax(Double invoiceAmountExclTax) {
		this.invoiceAmountExclTax = invoiceAmountExclTax;
	}

	public Double getInvoiceTaxAmount() {
		return invoiceTaxAmount;
	}

	public void setInvoiceTaxAmount(Double invoiceTaxAmount) {
		this.invoiceTaxAmount = invoiceTaxAmount;
	}

	public Double getInvoiceTotalAmountInclTax() {
		return invoiceTotalAmountInclTax;
	}

	public void setInvoiceTotalAmountInclTax(Double invoiceTotalAmountInclTax) {
		this.invoiceTotalAmountInclTax = invoiceTotalAmountInclTax;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Date getDateSentOrReceived() {
		return dateSentOrReceived;
	}

	public void setDateSentOrReceived(Date dateSentOrReceived) {
		this.dateSentOrReceived = dateSentOrReceived;
	}

	public String getFromParticipantName() {
		return fromParticipantName;
	}

	public void setFromParticipantName(String fromParticipantName) {
		this.fromParticipantName = fromParticipantName;
	}

	public String getFromAddress() {
		return fromAddress;
	}

	public void setFromAddress(String fromAddress) {
		this.fromAddress = fromAddress;
	}

	public String getFromVatNumber() {
		return fromVatNumber;
	}

	public void setFromVatNumber(String fromVatNumber) {
		this.fromVatNumber = fromVatNumber;
	}

	public String getFromEmailAddress() {
		return fromEmailAddress;
	}

	public void setFromEmailAddress(String fromEmailAddress) {
		this.fromEmailAddress = fromEmailAddress;
	}

	public String getFromPhoneNumber() {
		return fromPhoneNumber;
	}

	public void setFromPhoneNumber(String fromPhoneNumber) {
		this.fromPhoneNumber = fromPhoneNumber;
	}

	public String getFromBankDetails() {
		return fromBankDetails;
	}

	public void setFromBankDetails(String fromBankDetails) {
		this.fromBankDetails = fromBankDetails;
	}

	public String getFromThankYouMsg() {
		return fromThankYouMsg;
	}

	public void setFromThankYouMsg(String fromThankYouMsg) {
		this.fromThankYouMsg = fromThankYouMsg;
	}

	public String getToParticipantName() {
		return toParticipantName;
	}

	public void setToParticipantName(String toParticipantName) {
		this.toParticipantName = toParticipantName;
	}

	public String getToAddress() {
		return toAddress;
	}

	public void setToAddress(String toAddress) {
		this.toAddress = toAddress;
	}

	public String getToVatNumber() {
		return toVatNumber;
	}

	public void setToVatNumber(String toVatNumber) {
		this.toVatNumber = toVatNumber;
	}

	public String getToEmailAddress() {
		return toEmailAddress;
	}

	public void setToEmailAddress(String toEmailAddress) {
		this.toEmailAddress = toEmailAddress;
	}

	public String getToPhoneNumber() {
		return toPhoneNumber;
	}

	public void setToPhoneNumber(String toPhoneNumber) {
		this.toPhoneNumber = toPhoneNumber;
	}

	public String getToAttention() {
		return toAttention;
	}

	public void setToAttention(String toAttention) {
		this.toAttention = toAttention;
	}

	public Date getLastUpdateTimestamp() {
		return lastUpdateTimestamp;
	}

	public void setLastUpdateTimestamp(Date lastUpdateTimestamp) {
		this.lastUpdateTimestamp = lastUpdateTimestamp;
	}

	public String getLastUpdateUserName() {
		return lastUpdateUserName;
	}

	public void setLastUpdateUserName(String lastUpdateUserName) {
		this.lastUpdateUserName = lastUpdateUserName;
	}


}