package net.integrategroup.ignite.persistence.model;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import com.fasterxml.jackson.databind.annotation.JsonSerialize;

import net.integrategroup.ignite.utils.JsonDateSerializer;

/** @author Generated by Johannes Marais (JohannesSQL) */

@Entity
@Table(schema = "ig_db", name = "ProcedureRelatedDocs")
public class ProcedureRelatedDocs implements Serializable {


	private static final long serialVersionUID = -4001556949012486240L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "ProcedureRelatedDocsId")
	private Long procedureRelatedDocsId;

	@Column(name = "GenProcedureId")
	private Long genProcedureId;

	@Column(name = "RelatedDocsId")
	private Long relatedDocsId;

	@JsonSerialize(using = JsonDateSerializer.class)
	@Column(name = "LastUpdateTimestamp")
	private Date lastUpdateTimestamp;

	@Column(name = "LastUpdateUserName")
	private String lastUpdateUserName;




	public Long getProcedureRelatedDocsId() {
		return procedureRelatedDocsId;
	}

	public void setProcedureRelatedDocsId(Long procedureRelatedDocsId) {
		this.procedureRelatedDocsId = procedureRelatedDocsId;
	}

	public Long getGenProcedureId() {
		return genProcedureId;
	}

	public void setGenProcedureId(Long genProcedureId) {
		this.genProcedureId = genProcedureId;
	}

	public Long getRelatedDocsId() {
		return relatedDocsId;
	}

	public void setRelatedDocsId(Long relatedDocsId) {
		this.relatedDocsId = relatedDocsId;
	}

	public Date getLastUpdateTimestamp() {
		return lastUpdateTimestamp;
	}

	public void setLastUpdateTimestamp(Date lastUpdateTimestamp) {
		this.lastUpdateTimestamp = lastUpdateTimestamp;
	}

	public String getLastUpdateUserName() {
		return lastUpdateUserName;
	}

	public void setLastUpdateUserName(String lastUpdateUserName) {
		this.lastUpdateUserName = lastUpdateUserName;
	}


}