package net.integrategroup.ignite.persistence.model;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import com.fasterxml.jackson.databind.annotation.JsonSerialize;

import net.integrategroup.ignite.utils.JsonDateSerializer;

/** @author Generated by Johannes Marais (JohannesSQL v4.6) **/
/** ******* ********* ** 2023-06-08 11:33:15 ******** ***** **/

@Entity
@Table(schema = "ig_db", name = "ProjectSdStage")
public class ProjectSdStage implements Serializable {


    /**
	 *
	 */
	private static final long serialVersionUID = 206928473783097960L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "ProjectSdStageId")
	private Long projectSdStageId;

	@Column(name = "ProjectSdId")
	private Long projectSdId;

	@Column(name = "ProjectStageId")
	private Long projectStageId;

	@Column(name = "LastUpdateUserName")
	private String lastUpdateUserName;

	@JsonSerialize(using = JsonDateSerializer.class)
	@Column(name = "LastUpdateTimestamp")
	private Date lastUpdateTimestamp;




	public Long getProjectSdStageId() {
		return projectSdStageId;
	}

	public void setProjectSdStageId(Long projectSdStageId) {
		this.projectSdStageId = projectSdStageId;
	}

	public Long getProjectSdId() {
		return projectSdId;
	}

	public void setProjectSdId(Long projectSdId) {
		this.projectSdId = projectSdId;
	}

	public Long getProjectStageId() {
		return projectStageId;
	}

	public void setProjectStageId(Long projectStageId) {
		this.projectStageId = projectStageId;
	}

	public String getLastUpdateUserName() {
		return lastUpdateUserName;
	}

	public void setLastUpdateUserName(String lastUpdateUserName) {
		this.lastUpdateUserName = lastUpdateUserName;
	}

	public Date getLastUpdateTimestamp() {
		return lastUpdateTimestamp;
	}

	public void setLastUpdateTimestamp(Date lastUpdateTimestamp) {
		this.lastUpdateTimestamp = lastUpdateTimestamp;
	}


}

/**  javascript
		{ data: "projectSdStageId" },         //0 MySql-TableName: ProjectSdStage
		{ data: "projectSdId" },              //1
		{ data: "projectStageId" },           //2
		{ data: "lastUpdateUserName" },       //3
		{ data: "lastUpdateTimestamp" },      //4

/**  html
										<th>ProjectSdStageId</th>         <!--0  MySql-TableName: ProjectSdStage-->
										<th>ProjectSdId</th>              <!--1  ProjectSdId-->
										<th>ProjectStageId</th>           <!--2  ProjectStageId-->
										<th>LastUpdateUserName</th>       <!--3  LastUpdateUserName-->
										<th>LastUpdateTimestamp</th>      <!--4  LastUpdateTimestamp-->

*/