package net.integrategroup.ignite.persistence.model;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import com.fasterxml.jackson.databind.annotation.JsonSerialize;

import net.integrategroup.ignite.utils.JsonDateSerializer;

/** @author Generated by Johannes Marais (JohannesSQL) **/
/** 2023-04-09 20:16:36 **/

@Entity
@Table(schema = "ig_db", name = "ResourceRemuneration")
public class ResourceRemuneration implements Serializable {


    /**
	 *
	 */
	private static final long serialVersionUID = 7363685821137065591L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "ResourceRemunerationId")
	private Long resourceRemunerationId;

	@Column(name = "NonProjectRelatedAgreementId")
	private Long nonProjectRelatedAgreementId;

//	@OneToOne(targetEntity = NonProjectRelatedAgreement.class)
//	@JoinColumn(name = "NonProjectRelatedAgreementId", referencedColumnName = "NonProjectRelatedAgreementId", nullable = true, insertable = false, updatable = false)
//	private NonProjectRelatedAgreement nonProjectRelatedAgreement;

	@Column(name = "ResourceRemunTypeId")
	private Long resourceRemunTypeId;

//	@OneToOne(targetEntity = ResourceRemunType.class)
//	@JoinColumn(name = "ResourceRemunTypeId", referencedColumnName = "ResourceRemunTypeId", nullable = true, insertable = false, updatable = false)
//	private ResourceRemunType resourceRemunType;

	@Column(name = "Description")
	private String description;

	@JsonSerialize(using = JsonDateSerializer.class)
	@Column(name = "StartDate")
	private Date startDate;

	@JsonSerialize(using = JsonDateSerializer.class)
	@Column(name = "EndDate")
	private Date endDate;

	@Column(name = "Amount")
	private Double amount;

	@Column(name = "AllowExpenseDeductions")
	private String allowExpenseDeductions;

	@JsonSerialize(using = JsonDateSerializer.class)
	@Column(name = "LastUpdateTimestamp")
	private Date lastUpdateTimestamp;

	@Column(name = "LastUpdateUserName")
	private String lastUpdateUserName;




	public Long getResourceRemunerationId() {
		return resourceRemunerationId;
	}

	public void setResourceRemunerationId(Long resourceRemunerationId) {
		this.resourceRemunerationId = resourceRemunerationId;
	}

	public Long getNonProjectRelatedAgreementId() {
		return nonProjectRelatedAgreementId;
	}

	public void setNonProjectRelatedAgreementId(Long nonProjectRelatedAgreementId) {
		this.nonProjectRelatedAgreementId = nonProjectRelatedAgreementId;
	}

//	public NonProjectRelatedAgreement getNonProjectRelatedAgreement() {
//		return nonProjectRelatedAgreement;
//	}
//
//	public void setNonProjectRelatedAgreement(NonProjectRelatedAgreement nonProjectRelatedAgreement) {
//		this.nonProjectRelatedAgreement = nonProjectRelatedAgreement;
//	}

	public Long getResourceRemunTypeId() {
		return resourceRemunTypeId;
	}

	public void setResourceRemunTypeId(Long resourceRemunTypeId) {
		this.resourceRemunTypeId = resourceRemunTypeId;
	}

//	public ResourceRemunType getResourceRemunType() {
//		return resourceRemunType;
//	}
//
//	public void setResourceRemunType(ResourceRemunType resourceRemunType) {
//		this.resourceRemunType = resourceRemunType;
//	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Date getStartDate() {
		return startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public Double getAmount() {
		return amount;
	}

	public void setAmount(Double amount) {
		this.amount = amount;
	}

	public String getAllowExpenseDeductions() {
		return allowExpenseDeductions;
	}

	public void setAllowExpenseDeductions(String allowExpenseDeductions) {
		this.allowExpenseDeductions = allowExpenseDeductions;
	}

	public Date getLastUpdateTimestamp() {
		return lastUpdateTimestamp;
	}

	public void setLastUpdateTimestamp(Date lastUpdateTimestamp) {
		this.lastUpdateTimestamp = lastUpdateTimestamp;
	}

	public String getLastUpdateUserName() {
		return lastUpdateUserName;
	}

	public void setLastUpdateUserName(String lastUpdateUserName) {
		this.lastUpdateUserName = lastUpdateUserName;
	}


}