package net.integrategroup.ignite.persistence.model;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import com.fasterxml.jackson.databind.annotation.JsonSerialize;

import net.integrategroup.ignite.utils.JsonDateSerializer;

/** @author Generated by Johannes Marais (JohannesSQL v7.7) **/
/** ******* ********* ** 2023-10-22 07:09:40 ******** *ssi* **/

@Entity
@Table(schema = "ig_db", name = "StudyInstitute")
public class StudyInstitute implements Serializable {


    private static final long serialVersionUID = 520703737315972475L; /** ID was Generated by Johannes **/


    @Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "StudyInstituteId")
	private Long studyInstituteId;

	@Column(name = "Name")
	private String name;

	@Column(name = "ShortName")
	private String shortName;

	@Column(name = "Description")
	private String description;

	@JsonSerialize(using = JsonDateSerializer.class)
	@Column(name = "LastUpdateTimestamp")
	private Date lastUpdateTimestamp;

	@Column(name = "LastUpdateUserName")
	private String lastUpdateUserName;




	public Long getStudyInstituteId() {
		return studyInstituteId;
	}

	public void setStudyInstituteId(Long studyInstituteId) {
		this.studyInstituteId = studyInstituteId;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getShortName() {
		return shortName;
	}

	public void setShortName(String shortName) {
		this.shortName = shortName;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Date getLastUpdateTimestamp() {
		return lastUpdateTimestamp;
	}

	public void setLastUpdateTimestamp(Date lastUpdateTimestamp) {
		this.lastUpdateTimestamp = lastUpdateTimestamp;
	}

	public String getLastUpdateUserName() {
		return lastUpdateUserName;
	}

	public void setLastUpdateUserName(String lastUpdateUserName) {
		this.lastUpdateUserName = lastUpdateUserName;
	}


}

/**  javascript      vir grid population        (jsStr)

	var columnsArray = [
		 { data: "studyInstituteId" }         //0 MySql-TableName: StudyInstitute
		,{ data: "name" }                     //1
		,{ data: "shortName" }                //2
		,{ data: "description" }              //3
		,{ data: "lastUpdateTimestamp" }      //4
		,{ data: "lastUpdateUserName" }       //5
	];

	var columnDefsArray = [
		{
			visible: false,
			targets: [0, 5]
		}
		,{       //for Date columns
			render: function (data, type, row) {
				var html = data;
				if (type == "display") {
					html = timestampToString(data, false);
				}
				return html;
			},
			targets: [4]
		}
	];







/**  javascript      vir grid SelectFromGridDialog        (js1Str)

	var columns = [
		{ data: "studyInstituteId", name: "StudyInstituteId" }             //0 MySql-TableName: StudyInstitute
		,{ data: "name", name: "Name" }                                     //1
		,{ data: "shortName", name: "ShortName" }                           //2
		,{ data: "description", name: "Description" }                       //3
		,{ data: "lastUpdateTimestamp", name: "LastUpdateTimestamp" }       //4
		,{ data: "lastUpdateUserName", name: "LastUpdateUserName" }         //5
	];

	var columnDefs = [
		{
			visible: false,
			targets: [0, 5]
		}
		,{       //for Date columns
			render: function (data, type, row) {
				var html = data;
				if (type == "display") {
					html = timestampToString(data, false);
				}
				return html;
			},
			targets: [4]
		}
	];







Vir 'n Save Data function                        (js2Str)


	var postUrl = "/rest/ignite/v1/study-institute/new";
	var postData = {
		studyInstituteId : $("#ssiStudyInstituteId").val()         //0 MySql-TableName: StudyInstitute
		,name : $("#ssiName").val()                                                  //1
		,shortName : $("#ssiShortName").val()                                        //2
		,description : $("#ssiDescription").val()                                    //3
		,lastUpdateTimestamp : getMsFromDatePicker("ssiLastUpdateTimestamp")         //4
	};

	var errors = "";






Vir 'n Populate Data function                                                  (js3Str)

		//  MySql-TableName: StudyInstitute										   (js3Str)
		$("#ssiStudyInstituteId").val(data.studyInstituteId);             //0
		$("#ssiName").val(data.name);                                     //1
		$("#ssiShortName").val(data.shortName);                           //2
		$("#ssiDescription").val(data.description);                       //3
		$("#ssiLastUpdateTimestamp").datepicker("setDate", data.lastUpdateTimestamp == null? timestampToString(new Date(), false) : new Date(data.lastUpdateTimestamp));       //4






/**  HTML  om 'n grid te populate
												<th>StudyInstituteId</th>            <!--0  MySql-TableName: StudyInstitute-->
												<th>Name</th>                        <!--1  Name-->
												<th>Short Name</th>                  <!--2  ShortName-->
												<th>Description</th>                 <!--3  Description-->
												<th>Last Update Timestamp</th>       <!--4  LastUpdateTimestamp-->
												<th>LastUpdateUserName</th>          <!--5  LastUpdateUserName-->

*/