package net.integrategroup.ignite.persistence.model;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.databind.annotation.JsonSerialize;

import net.integrategroup.ignite.utils.JsonDateSerializer;

/** @author Generated by Johannes Marais (JohannesSQL) */

@Entity
@Table(schema = "ig_db", name = "Task")
public class Task implements Serializable {

	private static final long serialVersionUID = -6960590270194835121L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "TaskId")
	private Long taskId;

	@Column(name = "AssignmentId")
	private Long assignmentId;

	@Column(name = "TaskImportanceTypeId")
	private Long taskImportanceTypeId;

	@OneToOne(targetEntity = TaskImportanceType.class)
	@JoinColumn(name = "TaskImportanceTypeId", referencedColumnName = "TaskImportanceTypeId", nullable = true, insertable = false, updatable = false)
	private TaskImportanceType taskImportanceType;


	@Column(name = "OrderNumber")
	private String orderNumber;

	@Column(name = "TaskNumber")
	private String taskNumber;

	@Column(name = "Name")
	private String name;

	@Column(name = "Description")
	private String description;

	@JsonSerialize(using = JsonDateSerializer.class)
	@Column(name = "StartDate")
	private Date startDate;

	@Column(name = "DurationDays")
	private Long durationDays;

	@Column(name = "DurationHours")
	private Long durationHours;

	@JsonSerialize(using = JsonDateSerializer.class)
	@Column(name = "TimeOfDay")
	private Date timeOfDay;

	@Column(name = "Completed")
	private String completed;

	@JsonSerialize(using = JsonDateSerializer.class)
	@Column(name = "LastUpdateTimestamp")
	private Date lastUpdateTimestamp;

	@Column(name = "LastUpdateUserName")
	private String lastUpdateUserName;




	public TaskImportanceType getTaskImportanceType() {
		return taskImportanceType;
	}

	public void setTaskImportanceType(TaskImportanceType taskImportanceType) {
		this.taskImportanceType = taskImportanceType;
	}

	public Long getTaskId() {
		return taskId;
	}

	public void setTaskId(Long taskId) {
		this.taskId = taskId;
	}

	public Long getAssignmentId() {
		return assignmentId;
	}

	public void setAssignmentId(Long assignmentId) {
		this.assignmentId = assignmentId;
	}

	public Long getTaskImportanceTypeId() {
		return taskImportanceTypeId;
	}

	public void setTaskImportanceTypeId(Long taskImportanceTypeId) {
		this.taskImportanceTypeId = taskImportanceTypeId;
	}

	public String getOrderNumber() {
		return orderNumber;
	}

	public void setOrderNumber(String orderNumber) {
		this.orderNumber = orderNumber;
	}

	public String getTaskNumber() {
		return taskNumber;
	}

	public void setTaskNumber(String taskNumber) {
		this.taskNumber = taskNumber;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Date getStartDate() {
		return startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Long getDurationDays() {
		return durationDays;
	}

	public void setDurationDays(Long durationDays) {
		this.durationDays = durationDays;
	}

	public Long getDurationHours() {
		return durationHours;
	}

	public void setDurationHours(Long durationHours) {
		this.durationHours = durationHours;
	}

	public Date getTimeOfDay() {
		return timeOfDay;
	}

	public void setTimeOfDay(Date timeOfDay) {
		this.timeOfDay = timeOfDay;
	}

	public String getCompleted() {
		return completed;
	}

	public void setCompleted(String completed) {
		this.completed = completed;
	}

	public Date getLastUpdateTimestamp() {
		return lastUpdateTimestamp;
	}

	public void setLastUpdateTimestamp(Date lastUpdateTimestamp) {
		this.lastUpdateTimestamp = lastUpdateTimestamp;
	}

	public String getLastUpdateUserName() {
		return lastUpdateUserName;
	}

	public void setLastUpdateUserName(String lastUpdateUserName) {
		this.lastUpdateUserName = lastUpdateUserName;
	}


}