package net.integrategroup.ignite.persistence.model;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import com.fasterxml.jackson.databind.annotation.JsonSerialize;

import net.integrategroup.ignite.utils.JsonDateSerializer;

/** @author Generated by Johannes Marais (JohannesSQL) */

@Entity
@Table(schema = "ig_db", name = "TaskSubmission")
public class TaskSubmission implements Serializable {


	private static final long serialVersionUID = 1175962583771803239L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "TaskSubmissionId")
	private Long taskSubmissionId;

	@Column(name = "TaskRevisionId")
	private Long taskRevisionId;

	@Column(name = "SubmissionNumber")
	private Long submissionNumber;

	@JsonSerialize(using = JsonDateSerializer.class)
	@Column(name = "SubmissionDate")
	private Date submissionDate;

	@Column(name = "Acceptedflag")
	private String acceptedflag;

	@Column(name = "Comment")
	private String comment;

	@Column(name = "Feedback")
	private String feedback;

	@JsonSerialize(using = JsonDateSerializer.class)
	@Column(name = "LastUpdateTimestamp")
	private Date lastUpdateTimestamp;

	@Column(name = "LastUpdateUserName")
	private String lastUpdateUserName;




	public Long getTaskSubmissionId() {
		return taskSubmissionId;
	}

	public void setTaskSubmissionId(Long taskSubmissionId) {
		this.taskSubmissionId = taskSubmissionId;
	}

	public Long getTaskRevisionId() {
		return taskRevisionId;
	}

	public void setTaskRevisionId(Long taskRevisionId) {
		this.taskRevisionId = taskRevisionId;
	}

	public Long getSubmissionNumber() {
		return submissionNumber;
	}

	public void setSubmissionNumber(Long submissionNumber) {
		this.submissionNumber = submissionNumber;
	}

	public Date getSubmissionDate() {
		return submissionDate;
	}

	public void setSubmissionDate(Date submissionDate) {
		this.submissionDate = submissionDate;
	}

	public String getAcceptedflag() {
		return acceptedflag;
	}

	public void setAcceptedflag(String acceptedflag) {
		this.acceptedflag = acceptedflag;
	}

	public String getComment() {
		return comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public String getFeedback() {
		return feedback;
	}

	public void setFeedback(String feedback) {
		this.feedback = feedback;
	}

	public Date getLastUpdateTimestamp() {
		return lastUpdateTimestamp;
	}

	public void setLastUpdateTimestamp(Date lastUpdateTimestamp) {
		this.lastUpdateTimestamp = lastUpdateTimestamp;
	}

	public String getLastUpdateUserName() {
		return lastUpdateUserName;
	}

	public void setLastUpdateUserName(String lastUpdateUserName) {
		this.lastUpdateUserName = lastUpdateUserName;
	}


}