package net.integrategroup.ignite.persistence.model;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.databind.annotation.JsonSerialize;

import net.integrategroup.ignite.utils.JsonDateSerializer;

/** @author Generated by Johannes Marais (JohannesSQL v4.8) **/
/** ******* ********* ** 2023-06-27 10:41:57 ******** ***** **/

@Entity
@Table(schema = "ig_db", name = "Timesheet")
public class Timesheet implements Serializable {



	private static final long serialVersionUID = 5293381096018964555L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "TimesheetId")
	private Long timesheetId;

	@Column(name = "ProjectParticipantSdRoleId")
	private Long projectParticipantSdRoleId;

	@OneToOne(targetEntity = ProjectParticipantSdRole.class)
	@JoinColumn(name = "ProjectParticipantSdRoleId", referencedColumnName = "ProjectParticipantSdRoleId", nullable = true, insertable = false, updatable = false)
	private ProjectParticipantSdRole projectParticipantSd;

	@Column(name = "PpSdRoleStageId")
	private Long ppSdRoleStageId;

	@OneToOne(targetEntity = PpSdRoleStage.class)
	@JoinColumn(name = "PpSdRoleStageId", referencedColumnName = "PpSdRoleStageId", nullable = true, insertable = false, updatable = false)
	private PpSdRoleStage ppSdRoleStage;

	@Column(name = "ProjBasedRemunTypeId")
	private Long projBasedRemunTypeId;

	@OneToOne(targetEntity = ProjBasedRemunType.class)
	@JoinColumn(name = "ProjBasedRemunTypeId", referencedColumnName = "ProjBasedRemunTypeId", nullable = true, insertable = false, updatable = false)
	private ProjBasedRemunType projBasedRemunType;

	@Column(name = "AssignmentId")
	private Long assignmentId;

	@OneToOne(targetEntity = Assignment.class)
	@JoinColumn(name = "AssignmentId", referencedColumnName = "AssignmentId", nullable = true, insertable = false, updatable = false)
	private Assignment assignment;

	@Column(name = "TaskId")
	private Long taskId;

	@OneToOne(targetEntity = Task.class)
	@JoinColumn(name = "TaskId", referencedColumnName = "TaskId", nullable = true, insertable = false, updatable = false)
	private Task task;

	@JsonSerialize(using = JsonDateSerializer.class)
	@Column(name = "ActivityDate")
	private Date activityDate;

	@Column(name = "NumberOfUnits")
	private Double numberOfUnits;

	@Column(name = "Description")
	private String description;

	@Column(name = "LastUpdateUserName")
	private String lastUpdateUserName;

	@JsonSerialize(using = JsonDateSerializer.class)
	@Column(name = "LastUpdateTimestamp")
	private Date lastUpdateTimestamp;

	public Long getTimesheetId() {
		return timesheetId;
	}

	public void setTimesheetId(Long timesheetId) {
		this.timesheetId = timesheetId;
	}

	public Long getProjectParticipantSdRoleId() {
		return projectParticipantSdRoleId;
	}

	public void setProjectParticipantSdRoleId(Long projectParticipantSdRoleId) {
		this.projectParticipantSdRoleId = projectParticipantSdRoleId;
	}

	public ProjectParticipantSdRole getProjectParticipantSd() {
		return projectParticipantSd;
	}

	public void setProjectParticipantSd(ProjectParticipantSdRole projectParticipantSd) {
		this.projectParticipantSd = projectParticipantSd;
	}

	public Long getPpSdRoleStageId() {
		return ppSdRoleStageId;
	}

	public void setPpSdRoleStageId(Long ppSdRoleStageId) {
		this.ppSdRoleStageId = ppSdRoleStageId;
	}

	public PpSdRoleStage getPpSdRoleStage() {
		return ppSdRoleStage;
	}

	public void setPpSdRoleStage(PpSdRoleStage ppSdRoleStage) {
		this.ppSdRoleStage = ppSdRoleStage;
	}

	public Long getProjBasedRemunTypeId() {
		return projBasedRemunTypeId;
	}

	public void setProjBasedRemunTypeId(Long projBasedRemunTypeId) {
		this.projBasedRemunTypeId = projBasedRemunTypeId;
	}

	public ProjBasedRemunType getProjBasedRemunType() {
		return projBasedRemunType;
	}

	public void setProjBasedRemunType(ProjBasedRemunType projBasedRemunType) {
		this.projBasedRemunType = projBasedRemunType;
	}

	public Long getAssignmentId() {
		return assignmentId;
	}

	public void setAssignmentId(Long assignmentId) {
		this.assignmentId = assignmentId;
	}

	public Assignment getAssignment() {
		return assignment;
	}

	public void setAssignment(Assignment assignment) {
		this.assignment = assignment;
	}

	public Long getTaskId() {
		return taskId;
	}

	public void setTaskId(Long taskId) {
		this.taskId = taskId;
	}

	public Task getTask() {
		return task;
	}

	public void setTask(Task task) {
		this.task = task;
	}

	public Date getActivityDate() {
		return activityDate;
	}

	public void setActivityDate(Date activityDate) {
		this.activityDate = activityDate;
	}

	public Double getNumberOfUnits() {
		return numberOfUnits;
	}

	public void setNumberOfUnits(Double numberOfUnits) {
		this.numberOfUnits = numberOfUnits;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getLastUpdateUserName() {
		return lastUpdateUserName;
	}

	public void setLastUpdateUserName(String lastUpdateUserName) {
		this.lastUpdateUserName = lastUpdateUserName;
	}

	public Date getLastUpdateTimestamp() {
		return lastUpdateTimestamp;
	}

	public void setLastUpdateTimestamp(Date lastUpdateTimestamp) {
		this.lastUpdateTimestamp = lastUpdateTimestamp;
	}





}

/**  javascript
		{ data: "timesheetId" },              //0 MySql-TableName: Timesheet
		{ data: "projectParticipantSdRoleId" }, //1
		{ data: "ppSdRoleStageId" },          //2
		{ data: "projBasedRemunTypeId" },   //3
		{ data: "assignmentId" },             //4
		{ data: "taskId" },                   //5
		{ data: "activityDate" },             //6
		{ data: "numberOfUnits" },            //7
		{ data: "description" },              //8
		{ data: "lastUpdateUserName" },       //9
		{ data: "lastUpdateTimestamp" },      //10

/**  html
										<th>TimesheetId</th>              <!--0  MySql-TableName: Timesheet-->
										<th>ProjectParticipantSdRoleId</th> <!--1  ProjectParticipantSdRoleId-->
										<th>PpSdRoleStageId</th>          <!--2  PpSdRoleStageId-->
										<th>ProjBasedRemunTypeId</th>   <!--3  ProjBasedRemunTypeId-->
										<th>AssignmentId</th>             <!--4  AssignmentId-->
										<th>TaskId</th>                   <!--5  TaskId-->
										<th>ActivityDate</th>             <!--6  ActivityDate-->
										<th>NumberOfUnits</th>            <!--7  NumberOfUnits-->
										<th>Description</th>              <!--8  Description-->
										<th>LastUpdateUserName</th>       <!--9  LastUpdateUserName-->
										<th>LastUpdateTimestamp</th>      <!--10  LastUpdateTimestamp-->

*/