package net.integrategroup.ignite.persistence.model;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import com.fasterxml.jackson.databind.annotation.JsonSerialize;

import net.integrategroup.ignite.utils.JsonDateSerializer;

/** @author Generated by Johannes Marais (JohannesSQL) */

@Entity
@Table(schema = "ig_db", name = "UiComponent")
public class UiComponent implements Serializable {



	private static final long serialVersionUID = -4321305362747509766L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "UiComponentId")
	private Long uiComponentId;

	@Column(name = "ParentUiComponentId")
	private Long parentUiComponentId;

	@Column(name = "PermissionCodeRequired")
	private String permissionCodeRequired;

	@Column(name = "UiComponentTitle")
	private String uiComponentTitle;

	@Column(name = "UiComponentLink")
	private String uiComponentLink;

	@Column(name = "OrderNo")
	private Long orderNo;

	@Column(name = "ActiveInd")
	private String activeInd;

	@Column(name = "IconClassName")
	private String iconClassName;

	@JsonSerialize(using = JsonDateSerializer.class)
	@Column(name = "LastUpdateTimestamp")
	private Date lastUpdateTimestamp;

	@Column(name = "LastUpdateUserName")
	private String lastUpdateUserName;




	public Long getUiComponentId() {
		return uiComponentId;
	}

	public void setUiComponentId(Long uiComponentId) {
		this.uiComponentId = uiComponentId;
	}

	public Long getParentUiComponentId() {
		return parentUiComponentId;
	}

	public void setParentUiComponentId(Long parentUiComponentId) {
		this.parentUiComponentId = parentUiComponentId;
	}

	public String getPermissionCodeRequired() {
		return permissionCodeRequired;
	}

	public void setPermissionCodeRequired(String permissionCodeRequired) {
		this.permissionCodeRequired = permissionCodeRequired;
	}

	public String getUiComponentTitle() {
		return uiComponentTitle;
	}

	public void setUiComponentTitle(String uiComponentTitle) {
		this.uiComponentTitle = uiComponentTitle;
	}

	public String getUiComponentLink() {
		return uiComponentLink;
	}

	public void setUiComponentLink(String uiComponentLink) {
		this.uiComponentLink = uiComponentLink;
	}

	public Long getOrderNo() {
		return orderNo;
	}

	public void setOrderNo(Long orderNo) {
		this.orderNo = orderNo;
	}

	public String getActiveInd() {
		return activeInd;
	}

	public void setActiveInd(String activeInd) {
		this.activeInd = activeInd;
	}

	public String getIconClassName() {
		return iconClassName;
	}

	public void setIconClassName(String iconClassName) {
		this.iconClassName = iconClassName;
	}

	public Date getLastUpdateTimestamp() {
		return lastUpdateTimestamp;
	}

	public void setLastUpdateTimestamp(Date lastUpdateTimestamp) {
		this.lastUpdateTimestamp = lastUpdateTimestamp;
	}

	public String getLastUpdateUserName() {
		return lastUpdateUserName;
	}

	public void setLastUpdateUserName(String lastUpdateUserName) {
		this.lastUpdateUserName = lastUpdateUserName;
	}


}