package net.integrategroup.ignite.persistence.model;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import com.fasterxml.jackson.databind.annotation.JsonSerialize;

import net.integrategroup.ignite.utils.JsonDateSerializer;

/** @author Generated by Johannes Marais (JohannesSQL) */

@Entity
@Table(schema = "ig_db", name = "vAssignmentList")
public class VAssignmentList implements Serializable {



	private static final long serialVersionUID = 3609127427566841252L;

	@Id
	@Column(name = "AssignmentId")
	private Long assignmentId;

	@Column(name = "ProjectParticipantIdInstructor")
	private Long projectParticipantIdInstructor;

	@Column(name = "PpInstructorName")
	private String ppInstructorName;

	@Column(name = "IndividualIdInstructor")
	private Long individualIdInstructor;

	@Column(name = "IndividualInstructorName")
	private String individualInstructorName;

	@Column(name = "ProjectParticipantIdIndivResp")
	private Long projectParticipantIdIndivResp;

	@Column(name = "IndividualRespName")
	private String individualRespName;

	@Column(name = "IndividualIdLogger")
	private Long individualIdLogger;

	@Column(name = "IndividualLoggerName")
	private String individualLoggerName;

	@Column(name = "AssignmentGroupId")
	private Long assignmentGroupId;

	@Column(name = "AssignmentGroupName")
	private String assignmentGroupName;

	@Column(name = "AssignmentNumber")
	private String assignmentNumber;

	@Column(name = "Name")
	private String name;

	@Column(name = "Description")
	private String description;

	@JsonSerialize(using = JsonDateSerializer.class)
	@Column(name = "StartDate")
	private Date startDate;

	@JsonSerialize(using = JsonDateSerializer.class)
	@Column(name = "TimeOfDay")
	private Date timeOfDay;

	@Column(name = "RepeatCode")
	private String repeatCode;

	@JsonSerialize(using = JsonDateSerializer.class)
	@Column(name = "LastUpdateTimestamp")
	private Date lastUpdateTimestamp;

	@Column(name = "LastUpdateUserName")
	private String lastUpdateUserName;

	@Column(name = "ProjectId")
	private Long projectId;

	@Column(name = "ProjectAssignmentNumber")
	private String projectAssignmentNumber;

	@Column(name = "Title")
	private String title;

	@Column(name = "ProjectName")
	private String projectName;

	@Column(name = "Completed")
	private String completed;




	public Long getAssignmentId() {
		return assignmentId;
	}

	public void setAssignmentId(Long assignmentId) {
		this.assignmentId = assignmentId;
	}

	public Long getProjectParticipantIdInstructor() {
		return projectParticipantIdInstructor;
	}

	public void setProjectParticipantIdInstructor(Long projectParticipantIdInstructor) {
		this.projectParticipantIdInstructor = projectParticipantIdInstructor;
	}

	public String getPpInstructorName() {
		return ppInstructorName;
	}

	public void setPpInstructorName(String ppInstructorName) {
		this.ppInstructorName = ppInstructorName;
	}

	public Long getIndividualIdInstructor() {
		return individualIdInstructor;
	}

	public void setIndividualIdInstructor(Long individualIdInstructor) {
		this.individualIdInstructor = individualIdInstructor;
	}

	public String getIndividualInstructorName() {
		return individualInstructorName;
	}

	public void setIndividualInstructorName(String individualInstructorName) {
		this.individualInstructorName = individualInstructorName;
	}

	public Long getProjectParticipantIdIndivResp() {
		return projectParticipantIdIndivResp;
	}

	public void setProjectParticipantIdIndivResp(Long projectParticipantIdIndivResp) {
		this.projectParticipantIdIndivResp = projectParticipantIdIndivResp;
	}

	public String getIndividualRespName() {
		return individualRespName;
	}

	public void setIndividualRespName(String individualRespName) {
		this.individualRespName = individualRespName;
	}

	public Long getIndividualIdLogger() {
		return individualIdLogger;
	}

	public void setIndividualIdLogger(Long individualIdLogger) {
		this.individualIdLogger = individualIdLogger;
	}

	public String getIndividualLoggerName() {
		return individualLoggerName;
	}

	public void setIndividualLoggerName(String individualLoggerName) {
		this.individualLoggerName = individualLoggerName;
	}

	public Long getAssignmentGroupId() {
		return assignmentGroupId;
	}

	public void setAssignmentGroupId(Long assignmentGroupId) {
		this.assignmentGroupId = assignmentGroupId;
	}

	public String getAssignmentGroupName() {
		return assignmentGroupName;
	}

	public void setAssignmentGroupName(String assignmentGroupName) {
		this.assignmentGroupName = assignmentGroupName;
	}

	public String getAssignmentNumber() {
		return assignmentNumber;
	}

	public void setAssignmentNumber(String assignmentNumber) {
		this.assignmentNumber = assignmentNumber;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Date getStartDate() {
		return startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getTimeOfDay() {
		return timeOfDay;
	}

	public void setTimeOfDay(Date timeOfDay) {
		this.timeOfDay = timeOfDay;
	}

	public String getRepeatCode() {
		return repeatCode;
	}

	public void setRepeatCode(String repeatCode) {
		this.repeatCode = repeatCode;
	}

	public Date getLastUpdateTimestamp() {
		return lastUpdateTimestamp;
	}

	public void setLastUpdateTimestamp(Date lastUpdateTimestamp) {
		this.lastUpdateTimestamp = lastUpdateTimestamp;
	}

	public String getLastUpdateUserName() {
		return lastUpdateUserName;
	}

	public void setLastUpdateUserName(String lastUpdateUserName) {
		this.lastUpdateUserName = lastUpdateUserName;
	}

	public Long getProjectId() {
		return projectId;
	}

	public void setProjectId(Long projectId) {
		this.projectId = projectId;
	}

	public String getProjectAssignmentNumber() {
		return projectAssignmentNumber;
	}

	public void setProjectAssignmentNumber(String projectAssignmentNumber) {
		this.projectAssignmentNumber = projectAssignmentNumber;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getProjectName() {
		return projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	public String getCompleted() {
		return completed;
	}

	public void setCompleted(String completed) {
		this.completed = completed;
	}


}