package net.integrategroup.ignite.persistence.model;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import com.fasterxml.jackson.databind.annotation.JsonSerialize;

import net.integrategroup.ignite.utils.JsonDateSerializer;

/** @author Generated by Johannes Marais (JohannesSQL v4.8) **/
/** ******* ********* ** 2023-06-20 18:52:05 ******** ***** **/

@Entity
@Table(schema = "ig_db", name = "vBankTransactionLink")
public class VBankTransactionLink implements Serializable {


    /**
	 *
	 */
	private static final long serialVersionUID = 8663894433624373098L;

	@Id
	@Column(name = "bankTransactionLinkId")
	private Long bankTransactionLinkId;

	@Column(name = "bankTransactionId")
	private Long bankTransactionId;

	@Column(name = "invoiceId")
	private Long invoiceId;

	@Column(name = "projectExpenseId")
	private Long projectExpenseId;

	@Column(name = "participantIdApprovedLink")
	private Long participantIdApprovedLink;

	@Column(name = "linkAmount")
	private Double linkAmount;

	@JsonSerialize(using = JsonDateSerializer.class)
	@Column(name = "automaticCursorLinkCreated")
	private Date automaticCursorLinkCreated;

	@JsonSerialize(using = JsonDateSerializer.class)
	@Column(name = "linkApproved")
	private Date linkApproved;

	@Column(name = "description")
	private String description;

	@Column(name = "participantBankDetailsId")
	private Long participantBankDetailsId;

	@Column(name = "bankStatementId")
	private Long bankStatementId;

	@Column(name = "participantIdOnTransaction")
	private Long participantIdOnTransaction;

	@Column(name = "description1")
	private String description1;

	@Column(name = "description2")
	private String description2;

	@JsonSerialize(using = JsonDateSerializer.class)
	@Column(name = "transactionDate")
	private Date transactionDate;

	@Column(name = "amount")
	private Double amount;

	@Column(name = "fullyLinkedBt")
	private String fullyLinkedBt;

	@Column(name = "participantIdMadePurchase")
	private Long participantIdMadePurchase;

	@Column(name = "participantIdVendor")
	private Long participantIdVendor;

	@Column(name = "expenseTypeId")
	private Long expenseTypeId;

	@Column(name = "assetId")
	private Long assetId;

	@Column(name = "paymentMethodCode")
	private String paymentMethodCode;

	@Column(name = "bankCardIdUsed")
	private Long bankCardIdUsed;

	@Column(name = "participantBankDetailsIdUsed")
	private Long participantBankDetailsIdUsed;

	@Column(name = "taxDeductableCategoryId")
	private Long taxDeductableCategoryId;

	@Column(name = "paymentDescription")
	private String paymentDescription;

	@JsonSerialize(using = JsonDateSerializer.class)
	@Column(name = "purchaseDate")
	private Date purchaseDate;

	@Column(name = "numberOfUnits")
	private Double numberOfUnits;

	@Column(name = "amountPerUnit")
	private Double amountPerUnit;


	@Column(name = "noteToAccountant")
	private String noteToAccountant;

	@Column(name = "fullyLinkedPe")
	private String fullyLinkedPe;

	@Column(name = "bankReference")
	private String bankReference;

	@Column(name = "approvedBy")
	private String approvedBy;




	public Long getbankTransactionLinkId() {
		return bankTransactionLinkId;
	}

	public void setbankTransactionLinkId(Long bankTransactionLinkId) {
		this.bankTransactionLinkId = bankTransactionLinkId;
	}

	public Long getbankTransactionId() {
		return bankTransactionId;
	}

	public void setbankTransactionId(Long bankTransactionId) {
		this.bankTransactionId = bankTransactionId;
	}

	public Long getinvoiceId() {
		return invoiceId;
	}

	public void setinvoiceId(Long invoiceId) {
		this.invoiceId = invoiceId;
	}

	public Long getprojectExpenseId() {
		return projectExpenseId;
	}

	public void setprojectExpenseId(Long projectExpenseId) {
		this.projectExpenseId = projectExpenseId;
	}

	public Long getparticipantIdApprovedLink() {
		return participantIdApprovedLink;
	}

	public void setparticipantIdApprovedLink(Long participantIdApprovedLink) {
		this.participantIdApprovedLink = participantIdApprovedLink;
	}

	public Double getlinkAmount() {
		return linkAmount;
	}

	public void setlinkAmount(Double linkAmount) {
		this.linkAmount = linkAmount;
	}

	public Date getautomaticCursorLinkCreated() {
		return automaticCursorLinkCreated;
	}

	public void setautomaticCursorLinkCreated(Date automaticCursorLinkCreated) {
		this.automaticCursorLinkCreated = automaticCursorLinkCreated;
	}

	public Date getlinkApproved() {
		return linkApproved;
	}

	public void setlinkApproved(Date linkApproved) {
		this.linkApproved = linkApproved;
	}

	public String getdescription() {
		return description;
	}

	public void setdescription(String description) {
		this.description = description;
	}

	public Long getparticipantBankDetailsId() {
		return participantBankDetailsId;
	}

	public void setparticipantBankDetailsId(Long participantBankDetailsId) {
		this.participantBankDetailsId = participantBankDetailsId;
	}

	public Long getbankStatementId() {
		return bankStatementId;
	}

	public void setbankStatementId(Long bankStatementId) {
		this.bankStatementId = bankStatementId;
	}

	public Long getparticipantIdOnTransaction() {
		return participantIdOnTransaction;
	}

	public void setparticipantIdOnTransaction(Long participantIdOnTransaction) {
		this.participantIdOnTransaction = participantIdOnTransaction;
	}

	public String getdescription1() {
		return description1;
	}

	public void setdescription1(String description1) {
		this.description1 = description1;
	}

	public String getdescription2() {
		return description2;
	}

	public void setdescription2(String description2) {
		this.description2 = description2;
	}

	public Date gettransactionDate() {
		return transactionDate;
	}

	public void settransactionDate(Date transactionDate) {
		this.transactionDate = transactionDate;
	}

	public Double getamount() {
		return amount;
	}

	public void setamount(Double amount) {
		this.amount = amount;
	}

	public String getfullyLinkedBt() {
		return fullyLinkedBt;
	}

	public void setfullyLinkedBt(String fullyLinkedBt) {
		this.fullyLinkedBt = fullyLinkedBt;
	}

	public Long getparticipantIdMadePurchase() {
		return participantIdMadePurchase;
	}

	public void setparticipantIdMadePurchase(Long participantIdMadePurchase) {
		this.participantIdMadePurchase = participantIdMadePurchase;
	}

	public Long getparticipantIdVendor() {
		return participantIdVendor;
	}

	public void setparticipantIdVendor(Long participantIdVendor) {
		this.participantIdVendor = participantIdVendor;
	}

	public Long getexpenseTypeId() {
		return expenseTypeId;
	}

	public void setexpenseTypeId(Long expenseTypeId) {
		this.expenseTypeId = expenseTypeId;
	}

	public Long getassetId() {
		return assetId;
	}

	public void setassetId(Long assetId) {
		this.assetId = assetId;
	}

	public String getpaymentMethodCode() {
		return paymentMethodCode;
	}

	public void setpaymentMethodCode(String paymentMethodCode) {
		this.paymentMethodCode = paymentMethodCode;
	}

	public Long getbankCardIdUsed() {
		return bankCardIdUsed;
	}

	public void setbankCardIdUsed(Long bankCardIdUsed) {
		this.bankCardIdUsed = bankCardIdUsed;
	}

	public Long getparticipantBankDetailsIdUsed() {
		return participantBankDetailsIdUsed;
	}

	public void setparticipantBankDetailsIdUsed(Long participantBankDetailsIdUsed) {
		this.participantBankDetailsIdUsed = participantBankDetailsIdUsed;
	}

	public Long gettaxDeductableCategoryId() {
		return taxDeductableCategoryId;
	}

	public void settaxDeductableCategoryId(Long taxDeductableCategoryId) {
		this.taxDeductableCategoryId = taxDeductableCategoryId;
	}

	public String getpaymentDescription() {
		return paymentDescription;
	}

	public void setpaymentDescription(String paymentDescription) {
		this.paymentDescription = paymentDescription;
	}

	public Date getpurchaseDate() {
		return purchaseDate;
	}

	public void setpurchaseDate(Date purchaseDate) {
		this.purchaseDate = purchaseDate;
	}

	public Double getnumberOfUnits() {
		return numberOfUnits;
	}

	public void setnumberOfUnits(Double numberOfUnits) {
		this.numberOfUnits = numberOfUnits;
	}

	public Double getamountPerUnit() {
		return amountPerUnit;
	}

	public void setamountPerUnit(Double amountPerUnit) {
		this.amountPerUnit = amountPerUnit;
	}



	public String getnoteToAccountant() {
		return noteToAccountant;
	}

	public void setnoteToAccountant(String noteToAccountant) {
		this.noteToAccountant = noteToAccountant;
	}

	public String getfullyLinkedPe() {
		return fullyLinkedPe;
	}

	public void setfullyLinkedPe(String fullyLinkedPe) {
		this.fullyLinkedPe = fullyLinkedPe;
	}

	public String getbankReference() {
		return bankReference;
	}

	public void setbankReference(String bankReference) {
		this.bankReference = bankReference;
	}

	public String getapprovedBy() {
		return approvedBy;
	}

	public void setapprovedBy(String approvedBy) {
		this.approvedBy = approvedBy;
	}


}

/**  javascript
		{ data: "bankTransactionLinkId" },    //0 MySql-TableName: VBankTransactionLink
		{ data: "bankTransactionId" },        //1
		{ data: "invoiceId" },                //2
		{ data: "projectExpenseId" },         //3
		{ data: "participantIdApprovedLink" }, //4
		{ data: "linkAmount" },               //5
		{ data: "automaticCursorLinkCreated" }, //6
		{ data: "linkApproved" },             //7
		{ data: "description" },              //8
		{ data: "participantBankDetailsId" }, //9
		{ data: "bankStatementId" },          //10
		{ data: "participantIdOnTransaction" }, //11
		{ data: "description1" },             //12
		{ data: "description2" },             //13
		{ data: "transactionDate" },          //14
		{ data: "amount" },                   //15
		{ data: "fullyLinkedBt" },            //16
		{ data: "participantIdMadePurchase" }, //17
		{ data: "participantIdVendor" },      //18
		{ data: "expenseTypeId" },            //19
		{ data: "assetId" },                  //20
		{ data: "paymentMethodCode" },        //21
		{ data: "bankCardIdUsed" },           //22
		{ data: "participantBankDetailsIdUsed" }, //23
		{ data: "taxDeductableCategoryId" }, //24
		{ data: "paymentDescription" },       //25
		{ data: "purchaseDate" },             //26
		{ data: "numberOfUnits" },            //27
		{ data: "amountPerUnit" },            //28
		
		{ data: "noteToAccountant" },         //29
		{ data: "fullyLinkedPe" },            //30
		{ data: "bankReference" },            //31
		{ data: "approvedBy" },               //32

/**  html
										<th>bankTransactionLinkId</th>    <!--0  MySql-TableName: VBankTransactionLink-->
										<th>bankTransactionId</th>        <!--1  bankTransactionId-->
										<th>invoiceId</th>                <!--2  invoiceId-->
										<th>projectExpenseId</th>         <!--3  projectExpenseId-->
										<th>participantIdApprovedLink</th> <!--4  participantIdApprovedLink-->
										<th>linkAmount</th>               <!--5  linkAmount-->
										<th>automaticCursorLinkCreated</th> <!--6  automaticCursorLinkCreated-->
										<th>linkApproved</th>             <!--7  linkApproved-->
										<th>description</th>              <!--8  description-->
										<th>participantBankDetailsId</th> <!--9  participantBankDetailsId-->
										<th>bankStatementId</th>          <!--10  bankStatementId-->
										<th>participantIdOnTransaction</th> <!--11  participantIdOnTransaction-->
										<th>description1</th>             <!--12  description1-->
										<th>description2</th>             <!--13  description2-->
										<th>transactionDate</th>          <!--14  transactionDate-->
										<th>amount</th>                   <!--15  amount-->
										<th>fullyLinkedBt</th>            <!--16  fullyLinkedBt-->
										<th>participantIdMadePurchase</th> <!--17  participantIdMadePurchase-->
										<th>participantIdVendor</th>      <!--18  participantIdVendor-->
										<th>expenseTypeId</th>            <!--19  expenseTypeId-->
										<th>assetId</th>                  <!--20  assetId-->
										<th>paymentMethodCode</th>        <!--21  paymentMethodCode-->
										<th>bankCardIdUsed</th>           <!--22  bankCardIdUsed-->
										<th>participantBankDetailsIdUsed</th> <!--23  participantBankDetailsIdUsed-->
										<th>taxDeductableCategoryId</th> <!--24  taxDeductableCategoryId-->
										<th>paymentDescription</th>       <!--25  paymentDescription-->
										<th>purchaseDate</th>             <!--26  purchaseDate-->
										<th>numberOfUnits</th>            <!--27  numberOfUnits-->
										<th>amountPerUnit</th>            <!--28  amountPerUnit-->
							
										<th>noteToAccountant</th>         <!--29  noteToAccountant-->
										<th>fullyLinkedPe</th>            <!--30  fullyLinkedPe-->
										<th>bankReference</th>            <!--31  bankReference-->
										<th>approvedBy</th>               <!--32  approvedBy-->

*/