package net.integrategroup.ignite.persistence.model;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/** @author Generated by Johannes Marais (JohannesSQL v7.7) **/
/** ******* ********* ** 2023-10-17 18:12:49 ******** *iq* **/

@Entity
@Table(schema = "ig_db", name = "vInstituteQualification")
public class VInstituteQualification implements Serializable {


    private static final long serialVersionUID = 878460806286408825L; /** ID was Generated by Johannes **/


    @Id
	@Column(name = "InstituteQualificationId")
	private Long instituteQualificationId;

	@Column(name = "StudyInstituteId")
	private Long studyInstituteId;

/***	@OneToOne(targetEntity = StudyInstitute.class)
	@JoinColumn(name = "StudyInstituteId", referencedColumnName = "StudyInstituteId", nullable = true, insertable = false, updatable = false)
	private StudyInstitute studyInstitute; ***/

	@Column(name = "StudyInstituteId_Name")
	private String studyInstituteId_Name;

	@Column(name = "Name")
	private String name;

	@Column(name = "Description")
	private String description;

	@Column(name = "CombinedName")
	private String combinedName;




	public Long getInstituteQualificationId() {
		return instituteQualificationId;
	}

	public void setInstituteQualificationId(Long instituteQualificationId) {
		this.instituteQualificationId = instituteQualificationId;
	}

	public Long getStudyInstituteId() {
		return studyInstituteId;
	}

	public void setStudyInstituteId(Long studyInstituteId) {
		this.studyInstituteId = studyInstituteId;
	}

/***	public StudyInstitute getStudyInstitute() {
		return studyInstitute;
	}

	public void setStudyInstitute(StudyInstitute studyInstitute) {
		this.studyInstitute = studyInstitute;
	} ***/

	public String getStudyInstituteId_Name() {
		return studyInstituteId_Name;
	}

	public void setStudyInstituteId_Name(String studyInstituteId_Name) {
		this.studyInstituteId_Name = studyInstituteId_Name;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getCombinedName() {
		return combinedName;
	}

	public void setCombinedName(String combinedName) {
		this.combinedName = combinedName;
	}


}

/**  javascript      vir grid population        (jsStr)

	var columnsArray = [
		 { data: "instituteQualificationId" } //0 MySql-TableName: VInstituteQualification
		,{ data: "studyInstituteId" }         //1
		,{ data: "studyInstituteId_Name" }    //2
		,{ data: "name" }                     //3
		,{ data: "description" }              //4
		,{ data: "combinedName" }             //5
	];

	var columnDefsArray = [
		{
			visible: false,
			targets: [0, 1]
		}
	];







/**  javascript      vir grid SelectFromGridDialog        (js1Str)

	var columns = [
		{ data: "instituteQualificationId", name: "InstituteQualificationId" } //0 MySql-TableName: VInstituteQualification
		,{ data: "studyInstituteId", name: "StudyInstituteId" }             //1
		,{ data: "studyInstituteId_Name", name: "StudyInstituteId_Name" }   //2
		,{ data: "name", name: "Name" }                                     //3
		,{ data: "description", name: "Description" }                       //4
		,{ data: "combinedName", name: "CombinedName" }                     //5
	];

	var columnDefs = [
		{
			visible: false,
			targets: [0, 1]
		}
	];







Vir 'n Save Data function sien InstituteQualification.java






Vir 'n Populate Data function                                                  (js3Str)

		//  MySql-TableName: VInstituteQualification										   (js3Str)
		$("#iqInstituteQualificationId").val(data.instituteQualificationId); //0
		$("#iqStudyInstituteId").val(data.studyInstituteId);             //1
		populateSelect("iqStudyInstituteId",                              //name of html select element that will be populated
				"/rest/ignite/v1/study-institute/find-all",               //url
				"studyInstituteId",                                       //the value that must be saved (ReferencedColumnName)
				"name",                                                   //shown to user (usually a Name column)
				data.studyInstituteId,                                    //The selected one, if there is one
				true,                                                     //addEmpty, boolean: should we add empty object at the top
				null                                                      //completeMethod
		),

		$("#iqStudyInstituteId_Name").val(data.studyInstituteId_Name);   //2
		$("#iqName").val(data.name);                                     //3
		$("#iqDescription").val(data.description);                       //4
		$("#iqCombinedName").val(data.combinedName);                     //5






/**  HTML  om 'n grid te populate
												<th>InstituteQualificationId</th>    <!--0  MySql-TableName: VInstituteQualification-->
												<th>StudyInstituteId</th>            <!--1  StudyInstituteId-->
												<th>Study Institute Name</th>        <!--2  StudyInstituteId_Name-->
												<th>Name</th>                        <!--3  Name-->
												<th>Description</th>                 <!--4  Description-->
												<th>Combined Name</th>               <!--5  CombinedName-->

*/