package net.integrategroup.ignite.persistence.model;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/** @author Generated by Johannes Marais (JohannesSQL) **/
/** 2023-03-12 09:55:04 **/

@Entity
@Table(schema = "ig_db", name = "vParticipantBankDetails")
public class VParticipantBankDetails implements Serializable {

	private static final long serialVersionUID = 2847568990906848150L;

	@Id
	@Column(name = "ParticipantBankDetailsId")
	private Long participantBankDetailsId;

	@Column(name = "ParticipantIdOwner")
	private Long participantIdOwner;

	@Column(name = "BankId")
	private Long bankId;

	@Column(name = "BankCode")
	private String bankCode;

	@Column(name = "BankName")
	private String bankName;

	@Column(name = "AccountTypeId")
	private Long accountTypeId;

	@Column(name = "AccountName")
	private String accountName;

	@Column(name = "BranchId")
	private Long branchId;

	@Column(name = "BranchName")
	private String branchName;

	@Column(name = "BankDetailsName")
	private String name;

	@Column(name = "Description")
	private String description;

	@Column(name = "AccountHolderName")
	private String accountHolderName;

	@Column(name = "AccountNumber")
	private String accountNumber;

	@Column(name = "FlagDefault")
	private String flagDefault;

	@Column(name = "AccountDetails")
	private String accountDetails;

	public Long getParticipantBankDetailsId() {
		return participantBankDetailsId;
	}

	public void setParticipantBankDetailsId(Long participantBankDetailsId) {
		this.participantBankDetailsId = participantBankDetailsId;
	}

	public Long getParticipantIdOwner() {
		return participantIdOwner;
	}

	public void setParticipantIdOwner(Long participantIdOwner) {
		this.participantIdOwner = participantIdOwner;
	}

	public Long getBankId() {
		return bankId;
	}

	public void setBankId(Long bankId) {
		this.bankId = bankId;
	}

	public String getBankCode() {
		return bankCode;
	}

	public void setBankCode(String bankCode) {
		this.bankCode = bankCode;
	}

	public String getBankName() {
		return bankName;
	}

	public void setBankName(String bankName) {
		this.bankName = bankName;
	}

	public Long getAccountTypeId() {
		return accountTypeId;
	}

	public void setAccountTypeId(Long accountTypeId) {
		this.accountTypeId = accountTypeId;
	}

	public String getAccountName() {
		return accountName;
	}

	public void setAccountName(String accountName) {
		this.accountName = accountName;
	}

	public Long getBranchId() {
		return branchId;
	}

	public void setBranchId(Long branchId) {
		this.branchId = branchId;
	}

	public String getBranchName() {
		return branchName;
	}

	public void setBranchName(String branchName) {
		this.branchName = branchName;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getAccountHolderName() {
		return accountHolderName;
	}

	public void setAccountHolderName(String accountHolderName) {
		this.accountHolderName = accountHolderName;
	}

	public String getAccountNumber() {
		return accountNumber;
	}

	public void setAccountNumber(String accountNumber) {
		this.accountNumber = accountNumber;
	}
	
	public String getFlagDefault() {
		return flagDefault;
	}

	public void setFlagDefault(String flagDefault) {
		this.flagDefault = flagDefault;
	}

	public String getAccountDetails() {
		return accountDetails;
	}

	public void setAccountDetails(String accountDetails) {
		this.accountDetails = accountDetails;
	}

}