package net.integrategroup.ignite.persistence.model;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/** @author Generated by Johannes Marais (JohannesSQL) */

@Entity
@Table(schema = "ig_db", name = "vPersonResponsible")
public class VPersonResponsible implements Serializable {


	private static final long serialVersionUID = -4655507678461095520L;

	@Id
	@Column(name = "PersonResponsibleId")
	private Long personResponsibleId;

	@Column(name = "GenProcedureId")
	private Long genProcedureId;

	@Column(name = "RoleOnAProjectId")
	private Long roleOnAProjectId;

	@Column(name = "Name")
	private String name;

	@Column(name = "Abbreviation")
	private String abbreviation;

	@Column(name = "Description")
	private String description;




	public Long getPersonResponsibleId() {
		return personResponsibleId;
	}

	public void setPersonResponsibleId(Long personResponsibleId) {
		this.personResponsibleId = personResponsibleId;
	}

	public Long getGenProcedureId() {
		return genProcedureId;
	}

	public void setGenProcedureId(Long genProcedureId) {
		this.genProcedureId = genProcedureId;
	}

	public Long getRoleOnAProjectId() {
		return roleOnAProjectId;
	}

	public void setRoleOnAProjectId(Long roleOnAProjectId) {
		this.roleOnAProjectId = roleOnAProjectId;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAbbreviation() {
		return abbreviation;
	}

	public void setAbbreviation(String abbreviation) {
		this.abbreviation = abbreviation;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}


}