package net.integrategroup.ignite.persistence.model;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import com.fasterxml.jackson.databind.annotation.JsonSerialize;

import net.integrategroup.ignite.utils.JsonDateSerializer;

/** @author Generated by Johannes Marais (JohannesSQL v4.6) **/
/** ******* ********* ** 2023-06-09 13:06:16 ******** ***** **/

@Entity
@Table(schema = "ig_db", name = "vPpSdRoleStage")
public class VPpSdRoleStage implements Serializable {


    /**
	 *
	 */
	private static final long serialVersionUID = -3821290898253380624L;

	@Id
	@Column(name = "PpSdRoleStageId")
	private Long ppSdRoleStageId;

	@Column(name = "ProjectParticipantSdRoleId")
	private Long projectParticipantSdRoleId;

	@Column(name = "ProjectSdStageId")
	private Long projectSdStageId;

	@Column(name = "ProjectParticipantId")
	private Long projectParticipantId;

	@Column(name = "ProjectId")
	private Long projectId;

	@Column(name = "ParticipantId")
	private Long participantId;

	@Column(name = "ProjectSdId")
	private Long projectSdId;

	@Column(name = "ProjectStageId")
	private Long projectStageId;

	@Column(name = "OrderNumber")
	private Long orderNumber;

	@Column(name = "StageName")
	private String stageName;

	@Column(name = "Description")
	private String description;

	@JsonSerialize(using = JsonDateSerializer.class)
	@Column(name = "StartDate")
	private Date startDate;

	@JsonSerialize(using = JsonDateSerializer.class)
	@Column(name = "EndDate")
	private Date endDate;




	public Long getPpSdRoleStageId() {
		return ppSdRoleStageId;
	}

	public void setPpSdRoleStageId(Long ppSdRoleStageId) {
		this.ppSdRoleStageId = ppSdRoleStageId;
	}

	public Long getProjectParticipantSdRoleId() {
		return projectParticipantSdRoleId;
	}

	public void setProjectParticipantSdRoleId(Long projectParticipantSdRoleId) {
		this.projectParticipantSdRoleId = projectParticipantSdRoleId;
	}

	public Long getProjectSdStageId() {
		return projectSdStageId;
	}

	public void setProjectSdStageId(Long projectSdStageId) {
		this.projectSdStageId = projectSdStageId;
	}

	public Long getProjectParticipantId() {
		return projectParticipantId;
	}

	public void setProjectParticipantId(Long projectParticipantId) {
		this.projectParticipantId = projectParticipantId;
	}

	public Long getProjectId() {
		return projectId;
	}

	public void setProjectId(Long projectId) {
		this.projectId = projectId;
	}

	public Long getParticipantId() {
		return participantId;
	}

	public void setParticipantId(Long participantId) {
		this.participantId = participantId;
	}

	public Long getProjectSdId() {
		return projectSdId;
	}

	public void setProjectSdId(Long projectSdId) {
		this.projectSdId = projectSdId;
	}

	public Long getProjectStageId() {
		return projectStageId;
	}

	public void setProjectStageId(Long projectStageId) {
		this.projectStageId = projectStageId;
	}

	public Long getOrderNumber() {
		return orderNumber;
	}

	public void setOrderNumber(Long orderNumber) {
		this.orderNumber = orderNumber;
	}

	public String getStageName() {
		return stageName;
	}

	public void setStageName(String stageName) {
		this.stageName = stageName;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Date getStartDate() {
		return startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}


}

/**  javascript
		{ data: "ppSdRoleStageId" },          //0 MySql-TableName: VPpSdRoleStage
		{ data: "projectParticipantSdRoleId" }, //1
		{ data: "projectSdStageId" },         //2
		{ data: "projectParticipantId" },     //3
		{ data: "projectId" },                //4
		{ data: "participantId" },            //5
		{ data: "projectSdId" },              //6
		{ data: "projectStageId" },           //7
		{ data: "orderNumber" },              //8
		{ data: "stageName" },                //9
		{ data: "description" },              //10
		{ data: "startDate" },                //11
		{ data: "endDate" },                  //12

/**  html
										<th>PpSdRoleStageId</th>          <!--0  MySql-TableName: VPpSdRoleStage-->
										<th>ProjectParticipantSdRoleId</th> <!--1  ProjectParticipantSdRoleId-->
										<th>ProjectSdStageId</th>         <!--2  ProjectSdStageId-->
										<th>ProjectParticipantId</th>     <!--3  ProjectParticipantId-->
										<th>ProjectId</th>                <!--4  ProjectId-->
										<th>ParticipantId</th>            <!--5  ParticipantId-->
										<th>ProjectSdId</th>              <!--6  ProjectSdId-->
										<th>ProjectStageId</th>           <!--7  ProjectStageId-->
										<th>OrderNumber</th>              <!--8  OrderNumber-->
										<th>StageName</th>                <!--9  StageName-->
										<th>Description</th>              <!--10  Description-->
										<th>StartDate</th>                <!--11  StartDate-->
										<th>EndDate</th>                  <!--12  EndDate-->

*/