package net.integrategroup.ignite.persistence.model;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table(schema = "ig_db", name = "vProjectSd")
public class VProjectSd implements Serializable {


    private static final long serialVersionUID = 379710682297277325L; /** ID was Generated by Johannes **/

    @Id
	@Column(name = "ProjectSdId")
	private Long projectSdId;

    @Column(name = "RowNumber")
	private String rowNumber;

    @Column(name = "ParentName")
	private String parentName;

	@Column(name = "ServiceDisciplineIdParent")
	private Long serviceDisciplineIdParent;

	@Column(name = "Level")
	private Long level;

	@Column(name = "ServiceDisciplineId")
	private Long serviceDisciplineId;

	@Column(name = "ServiceDisciplineCode")
	private String serviceDisciplineCode;

	@Column(name = "ServiceDisciplineName")
	private String serviceDisciplineName;

	@Column(name = "SdCodeAndName")
	private String sdCodeAndName;

	@Column(name = "ProjectId")
	private Long projectId;

	@Column(name = "ServiceDisciplineIdIndustry")
	private Long serviceDisciplineIdIndustry;

	@Column(name = "IndustrySdName")
	private String industrySdName;



	public String getSdCodeAndName() {
		return sdCodeAndName;
	}

	public void setSdCodeAndName(String sdCodeAndName) {
		this.sdCodeAndName = sdCodeAndName;
	}

	public Long getProjectSdId() {
		return projectSdId;
	}

	public void setProjectSdId(Long projectSdId) {
		this.projectSdId = projectSdId;
	}

	public String getRowNumber() {
		return rowNumber;
	}

	public void setRowNumber(String rowNumber) {
		this.rowNumber = rowNumber;
	}

	public String getParentName() {
		return parentName;
	}

	public void setParentName(String parentName) {
		this.parentName = parentName;
	}

	public Long getServiceDisciplineIdParent() {
		return serviceDisciplineIdParent;
	}

	public void setServiceDisciplineIdParent(Long serviceDisciplineIdParent) {
		this.serviceDisciplineIdParent = serviceDisciplineIdParent;
	}

	public Long getLevel() {
		return level;
	}

	public void setLevel(Long level) {
		this.level = level;
	}

	public Long getServiceDisciplineId() {
		return serviceDisciplineId;
	}

	public void setServiceDisciplineId(Long serviceDisciplineId) {
		this.serviceDisciplineId = serviceDisciplineId;
	}

	public String getServiceDisciplineCode() {
		return serviceDisciplineCode;
	}

	public void setServiceDisciplineCode(String serviceDisciplineCode) {
		this.serviceDisciplineCode = serviceDisciplineCode;
	}

	public String getServiceDisciplineName() {
		return serviceDisciplineName;
	}

	public void setServiceDisciplineName(String serviceDisciplineName) {
		this.serviceDisciplineName = serviceDisciplineName;
	}

	public Long getProjectId() {
		return projectId;
	}

	public void setProjectId(Long projectId) {
		this.projectId = projectId;
	}

	public Long getServiceDisciplineIdIndustry() {
		return serviceDisciplineIdIndustry;
	}

	public void setServiceDisciplineIdIndustry(Long serviceDisciplineIdIndustry) {
		this.serviceDisciplineIdIndustry = serviceDisciplineIdIndustry;
	}

	public String getIndustrySdName() {
		return industrySdName;
	}

	public void setIndustrySdName(String industrySdName) {
		this.industrySdName = industrySdName;
	}


}