package net.integrategroup.ignite.persistence.model;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;


@Entity
@Table(schema = "ig_db", name = "vProvince")
public class VProvince implements Serializable {

    private static final long serialVersionUID = 385016256623005359L; /** ID was Generated by Johannes **/

    @Id
	@Column(name = "ProvinceId")
	private Long provinceId;

	@Column(name = "CountryId")
	private Long countryId;

	@Column(name = "CountryId_Name")
	private String countryId_Name;

	@Column(name = "CountryCodeAndName")
	private String countryCodeAndName;

	@Column(name = "CountryNameAndCode")
	private String countryNameAndCode;

	@Column(name = "ProvinceCode")
	private String provinceCode;

	@Column(name = "Name")
	private String name;

	@Column(name = "ProvinceCodeAndName")
	private String provinceCodeAndName;

	@Column(name = "ProvinceNameAndCode")
	private String provinceNameAndCode;


	public String getProvinceCode() {
		return provinceCode;
	}

	public void setProvinceCode(String provinceCode) {
		this.provinceCode = provinceCode;
	}

	public Long getProvinceId() {
		return provinceId;
	}

	public void setProvinceId(Long provinceId) {
		this.provinceId = provinceId;
	}

	public Long getCountryId() {
		return countryId;
	}

	public void setCountryId(Long countryId) {
		this.countryId = countryId;
	}

	public String getCountryId_Name() {
		return countryId_Name;
	}

	public void setCountryId_Name(String countryId_Name) {
		this.countryId_Name = countryId_Name;
	}

	public String getCountryCodeAndName() {
		return countryCodeAndName;
	}

	public void setCountryCodeAndName(String countryCodeAndName) {
		this.countryCodeAndName = countryCodeAndName;
	}

	public String getCountryNameAndCode() {
		return countryNameAndCode;
	}

	public void setCountryNameAndCode(String countryNameAndCode) {
		this.countryNameAndCode = countryNameAndCode;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getProvinceCodeAndName() {
		return provinceCodeAndName;
	}

	public void setProvinceCodeAndName(String provinceCodeAndName) {
		this.provinceCodeAndName = provinceCodeAndName;
	}

	public String getProvinceNameAndCode() {
		return provinceNameAndCode;
	}

	public void setProvinceNameAndCode(String provinceNameAndCode) {
		this.provinceNameAndCode = provinceNameAndCode;
	}


}