package net.integrategroup.ignite.persistence.model;

import java.io.Serializable;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/** @author Generated by Johannes Marais (JohannesSQL v?) **/
/** ******* ********* ** 2023-??? DON'T OVERWRITE THIS******/
/** ******* ********* ** 2023-??? DON'T OVERWRITE THIS******/


@Entity
@Table(schema = "ig_db", name = "vServiceDiscipline")
public class VServiceDiscipline implements Serializable {


    private static final long serialVersionUID = 690503555719044564L; /** ID was Generated by Johannes **/

    @Id
	@Column(name = "ServiceDisciplineId")
	private Long serviceDisciplineId;

	@Column(name = "ParentName")
	private String parentName;

	@Column(name = "ServiceDisciplineCode")
	private String serviceDisciplineCode;

	@Column(name = "ServiceDisciplineName")
	private String serviceDisciplineName;

	@Column(name = "Level")
	private Long level;

	@Column(name = "Name")
	private String name;

	@Column(name = "Description")
	private String description;

	@Column(name = "ServiceDisciplineIdParent")
	private Long serviceDisciplineIdParent;

	@Column(name = "ParentSdCode")
	private String parentSdCode;

	@Column(name = "ParentSdName")
	private String parentSdName;

	@Column(name = "ServiceDisciplineIdIndustry")
	private Long serviceDisciplineIdIndustry;

	@Column(name = "IndustrySdName")
	private String industrySdName;

	@OneToMany(targetEntity = VServiceDiscipline.class, fetch = FetchType.EAGER)
	@JoinColumn(name = "ServiceDisciplineIdParent", referencedColumnName = "ServiceDisciplineId", updatable = false, insertable = false, nullable = true)
	private List<VServiceDiscipline> children;

	@Column(name = "AnyChildren")
	private String anyChildren;

	@Column(name = "RowOrderNo")
	private Long rowOrderNo;

	@Column(name = "OrderNumber")
	private Long orderNumber;

	@Column(name = "AllowRoles")
	private String allowRoles;

	public Long getServiceDisciplineId() {
		return serviceDisciplineId;
	}

	public void setServiceDisciplineId(Long serviceDisciplineId) {
		this.serviceDisciplineId = serviceDisciplineId;
	}

	public String getParentName() {
		return parentName;
	}

	public void setParentName(String parentName) {
		this.parentName = parentName;
	}

	public String getServiceDisciplineCode() {
		return serviceDisciplineCode;
	}

	public void setServiceDisciplineCode(String serviceDisciplineCode) {
		this.serviceDisciplineCode = serviceDisciplineCode;
	}

	public String getServiceDisciplineName() {
		return serviceDisciplineName;
	}

	public void setServiceDisciplineName(String serviceDisciplineName) {
		this.serviceDisciplineName = serviceDisciplineName;
	}

	public Long getLevel() {
		return level;
	}

	public void setLevel(Long level) {
		this.level = level;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Long getServiceDisciplineIdParent() {
		return serviceDisciplineIdParent;
	}

	public void setServiceDisciplineIdParent(Long serviceDisciplineIdParent) {
		this.serviceDisciplineIdParent = serviceDisciplineIdParent;
	}

	public String getParentSdCode() {
		return parentSdCode;
	}

	public void setParentSdCode(String parentSdCode) {
		this.parentSdCode = parentSdCode;
	}

	public String getParentSdName() {
		return parentSdName;
	}

	public void setParentSdName(String parentSdName) {
		this.parentSdName = parentSdName;
	}

	public Long getServiceDisciplineIdIndustry() {
		return serviceDisciplineIdIndustry;
	}

	public void setServiceDisciplineIdIndustry(Long serviceDisciplineIdIndustry) {
		this.serviceDisciplineIdIndustry = serviceDisciplineIdIndustry;
	}

	public String getIndustrySdName() {
		return industrySdName;
	}

	public void setIndustrySdName(String industrySdName) {
		this.industrySdName = industrySdName;
	}

	public List<VServiceDiscipline> getChildren() {
		return children;
	}

	public void setChildren(List<VServiceDiscipline> children) {
		this.children = children;
	}

	public String getAnyChildren() {
		return anyChildren;
	}

	public void setAnyChildren(String anyChildren) {
		this.anyChildren = anyChildren;
	}

	public Long getRowOrderNo() {
		return rowOrderNo;
	}

	public void setRowOrderNo(Long rowOrderNo) {
		this.rowOrderNo = rowOrderNo;
	}

	public Long getOrderNumber() {
		return orderNumber;
	}

	public void setOrderNumber(Long orderNumber) {
		this.orderNumber = orderNumber;
	}

	public String getAllowRoles() {
		return allowRoles;
	}

	public void setAllowRoles(String allowRoles) {
		this.allowRoles = allowRoles;
	}

}
