package net.integrategroup.ignite.persistence.model;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import com.fasterxml.jackson.databind.annotation.JsonSerialize;

import net.integrategroup.ignite.utils.JsonDateSerializer;

/** @author Generated by Johannes Marais (JohannesSQL v4.8) **/
/** ******* ********* ** 2023-06-27 11:19:16 ******** ***** **/

@Entity
@Table(schema = "ig_db", name = "vTimesheet")
public class VTimesheet implements Serializable {

	private static final long serialVersionUID = 2983415460893789124L;

	@Id
	@Column(name = "TimesheetId")
	private Long timesheetId;

	@Column(name = "ProjectParticipantSdRoleId")
	private Long projectParticipantSdRoleId;

	@Column(name = "PpSdRoleStageId")
	private Long ppSdRoleStageId;

	@Column(name = "ProjBasedRemunTypeId")
	private Long projBasedRemunTypeId;

	@Column(name = "AssignmentId")
	private Long assignmentId;

	@Column(name = "TaskId")
	private Long taskId;

	@JsonSerialize(using = JsonDateSerializer.class)
	@Column(name = "ActivityDate")
	private Date activityDate;

	@Column(name = "NumberOfUnits")
	private Double numberOfUnits;

	@Column(name = "Description")
	private String description;

	@Column(name = "RemunerationTypeName")
	private String remunerationTypeName;

	@Column(name = "ProjectParticipantIdThatBookedTime")
	private Long projectParticipantIdThatBookedTime;

	@Column(name = "ProjectSdId")
	private Long projectSdId;

	@Column(name = "SdRoleId")
	private Long sdRoleId;

	@Column(name = "ParticipantIdThatBookedTime")
	private Long participantIdThatBookedTime;

	@Column(name = "SystemNameThatBookedTime")
	private String systemNameThatBookedTime;

	@Column(name = "SdId")
	private Long sdId;

	@Column(name = "SdCode")
	private String sdCode;

	@Column(name = "SdName")
	private String sdName;

	@Column(name = "RoleName")
	private String roleName;

	@Column(name = "RoleOnAProjectId")
	private Long roleOnAProjectId;

	@Column(name = "ProjectId")
	private Long projectId;

	@Column(name = "ProjectNumberText")
	private String projectNumberText;

	@Column(name = "ProjectNameText")
	private String projectNameText;

	@Column(name = "ParticipantIdHost")
	private Long participantIdHost;

	@Column(name = "ProjectParticipantIdLevel1")
	private Long projectParticipantIdLevel1;

	@Column(name = "ParticipantNameHost")
	private String participantNameHost;

	@Column(name = "UnitTypeCode")
	private String unitTypeCode;

	@Column(name = "UnitTypeName")
	private String unitTypeName;

	@Column(name = "ProjectSdStageId")
	private Long projectSdStageId;

	@Column(name = "ProjectStageId")
	private Long projectStageId;

	@Column(name = "StageName")
	private String stageName;



	public Long getSdId() {
		return sdId;
	}

	public void setSdId(Long sdId) {
		this.sdId = sdId;
	}

	public Long getTimesheetId() {
		return timesheetId;
	}

	public void setTimesheetId(Long timesheetId) {
		this.timesheetId = timesheetId;
	}

	public Long getProjectParticipantSdRoleId() {
		return projectParticipantSdRoleId;
	}

	public void setProjectParticipantSdRoleId(Long projectParticipantSdRoleId) {
		this.projectParticipantSdRoleId = projectParticipantSdRoleId;
	}

	public Long getPpSdRoleStageId() {
		return ppSdRoleStageId;
	}

	public void setPpSdRoleStageId(Long ppSdRoleStageId) {
		this.ppSdRoleStageId = ppSdRoleStageId;
	}

	public Long getProjBasedRemunTypeId() {
		return projBasedRemunTypeId;
	}

	public void setProjBasedRemunTypeId(Long projBasedRemunTypeId) {
		this.projBasedRemunTypeId = projBasedRemunTypeId;
	}

	public Long getAssignmentId() {
		return assignmentId;
	}

	public void setAssignmentId(Long assignmentId) {
		this.assignmentId = assignmentId;
	}

	public Long getTaskId() {
		return taskId;
	}

	public void setTaskId(Long taskId) {
		this.taskId = taskId;
	}

	public Date getActivityDate() {
		return activityDate;
	}

	public void setActivityDate(Date activityDate) {
		this.activityDate = activityDate;
	}

	public Double getNumberOfUnits() {
		return numberOfUnits;
	}

	public void setNumberOfUnits(Double numberOfUnits) {
		this.numberOfUnits = numberOfUnits;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getRemunerationTypeName() {
		return remunerationTypeName;
	}

	public void setRemunerationTypeName(String remunerationTypeName) {
		this.remunerationTypeName = remunerationTypeName;
	}

	public Long getProjectParticipantIdThatBookedTime() {
		return projectParticipantIdThatBookedTime;
	}

	public void setProjectParticipantIdThatBookedTime(Long projectParticipantIdThatBookedTime) {
		this.projectParticipantIdThatBookedTime = projectParticipantIdThatBookedTime;
	}

	public Long getProjectSdId() {
		return projectSdId;
	}

	public void setProjectSdId(Long projectSdId) {
		this.projectSdId = projectSdId;
	}

	public Long getSdRoleId() {
		return sdRoleId;
	}

	public void setSdRoleId(Long sdRoleId) {
		this.sdRoleId = sdRoleId;
	}

	public Long getParticipantIdThatBookedTime() {
		return participantIdThatBookedTime;
	}

	public void setParticipantIdThatBookedTime(Long participantIdThatBookedTime) {
		this.participantIdThatBookedTime = participantIdThatBookedTime;
	}

	public String getSystemNameThatBookedTime() {
		return systemNameThatBookedTime;
	}

	public void setSystemNameThatBookedTime(String systemNameThatBookedTime) {
		this.systemNameThatBookedTime = systemNameThatBookedTime;
	}

	public String getSdCode() {
		return sdCode;
	}

	public void setSdCode(String sdCode) {
		this.sdCode = sdCode;
	}

	public String getSdName() {
		return sdName;
	}

	public void setSdName(String sdName) {
		this.sdName = sdName;
	}

	public String getRoleName() {
		return roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	public Long getRoleOnAProjectId() {
		return roleOnAProjectId;
	}

	public void setRoleOnAProjectId(Long roleOnAProjectId) {
		this.roleOnAProjectId = roleOnAProjectId;
	}

	public Long getProjectId() {
		return projectId;
	}

	public void setProjectId(Long projectId) {
		this.projectId = projectId;
	}

	public String getProjectNumberText() {
		return projectNumberText;
	}

	public void setProjectNumberText(String projectNumberText) {
		this.projectNumberText = projectNumberText;
	}

	public String getProjectNameText() {
		return projectNameText;
	}

	public void setProjectNameText(String projectNameText) {
		this.projectNameText = projectNameText;
	}

	public Long getParticipantIdHost() {
		return participantIdHost;
	}

	public void setParticipantIdHost(Long participantIdHost) {
		this.participantIdHost = participantIdHost;
	}

	public Long getProjectParticipantIdLevel1() {
		return projectParticipantIdLevel1;
	}

	public void setProjectParticipantIdLevel1(Long projectParticipantIdLevel1) {
		this.projectParticipantIdLevel1 = projectParticipantIdLevel1;
	}

	public String getParticipantNameHost() {
		return participantNameHost;
	}

	public void setParticipantNameHost(String participantNameHost) {
		this.participantNameHost = participantNameHost;
	}

	public String getUnitTypeCode() {
		return unitTypeCode;
	}

	public void setUnitTypeCode(String unitTypeCode) {
		this.unitTypeCode = unitTypeCode;
	}

	public String getUnitTypeName() {
		return unitTypeName;
	}

	public void setUnitTypeName(String unitTypeName) {
		this.unitTypeName = unitTypeName;
	}

	public Long getProjectSdStageId() {
		return projectSdStageId;
	}

	public void setProjectSdStageId(Long projectSdStageId) {
		this.projectSdStageId = projectSdStageId;
	}

	public Long getProjectStageId() {
		return projectStageId;
	}

	public void setProjectStageId(Long projectStageId) {
		this.projectStageId = projectStageId;
	}

	public String getStageName() {
		return stageName;
	}

	public void setStageName(String stageName) {
		this.stageName = stageName;
	}

}
