package net.integrategroup.ignite.persistence.service;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import net.integrategroup.ignite.persistence.model.IndividualProfRegistration;
import net.integrategroup.ignite.persistence.model.VIndividualProfRegistration;
import net.integrategroup.ignite.persistence.repository.IndividualProfRegistrationRepository;

/** @author Generated by Johannes Marais (JohannesSQL v7.7) **/
/** ******* ********* ** 2023-10-16 19:51:56 ******** ***** **/

@Service
public class IndividualProfRegistrationServiceImpl implements IndividualProfRegistrationService {

	@Autowired
	IndividualProfRegistrationRepository individualProfRegistrationRepository;

	@Override
	public List<IndividualProfRegistration> findAll() {
		return individualProfRegistrationRepository.findAll();
	}

	@Override
	public IndividualProfRegistration getByIndividualProfRegistrationId(Long individualProfRegistrationId) {
		return individualProfRegistrationRepository.getByIndividualProfRegistrationId(individualProfRegistrationId);
	}

	@Override
	public IndividualProfRegistration save(IndividualProfRegistration individualProfRegistration) {
		return individualProfRegistrationRepository.save(individualProfRegistration);
	}

//	@Override                               //One record from View
//	public VIndividualProfRegistration getByVIndividualProfRegistrationId(Long individualProfRegistrationId) {
//		return individualProfRegistrationRepository.getByVIndividualProfRegistrationId(individualProfRegistrationId);
//	}


//	@Override								//All in view
//	public List<VIndividualProfRegistration> findListAllInView() {
//		return individualProfRegistrationRepository.findListAllInView();
//	}

//	@Override								//List from View without parameter
//	public List<VIndividualProfRegistration> findListIndividualProfRegistrationXXX() {
//		return individualProfRegistrationRepository.findListVIndividualProfRegistrationXXX();
//	}

	@Override								//List from View that needs parameter
	public List<VIndividualProfRegistration> findListVIndividualProfRegistrationForParticipant(Long participantId) {
		return individualProfRegistrationRepository.findListVIndividualProfRegistrationForParticipant(participantId);
	}

//	@Override								//List from View that needs multiple parameters
//	public List<VIndividualProfRegistration> findListIndividualProfRegistrationXXX(Long paramId, String paramName, String paramName2) {
//		return individualProfRegistrationRepository.findListVIndividualProfRegistrationXXX(paramId, paramName, paramName2);
//	}

//	@Override								//List from View that needs date parameters
//	public List<VIndividualProfRegistration> findListIndividualProfRegistrationXXX(Long paramId, Date fd, Date ld) {
//		return individualProfRegistrationRepository.findListVIndividualProfRegistrationXXX(paramId, fd, ld);
//	}



	@Override
	public List<IndividualProfRegistration> findListIndividualProfRegistrationForIndividualId(Long individualId) {
		return individualProfRegistrationRepository.findListIndividualProfRegistrationForIndividualId(individualId);
	}

	@Override
	public List<IndividualProfRegistration> findListIndividualProfRegistrationForProfessionalInstituteId(Long professionalInstituteId) {
		return individualProfRegistrationRepository.findListIndividualProfRegistrationForProfessionalInstituteId(professionalInstituteId);
	}



}