package net.integrategroup.ignite.persistence.service;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import net.integrategroup.ignite.persistence.model.InstituteQualification;
import net.integrategroup.ignite.persistence.model.VInstituteQualification;
import net.integrategroup.ignite.persistence.repository.InstituteQualificationRepository;

/** @author Generated by Johannes Marais (JohannesSQL v7.7) **/
/** ******* ********* ** 2023-10-16 19:51:56 ******** ***** **/

@Service
public class InstituteQualificationServiceImpl implements InstituteQualificationService {

	@Autowired
	InstituteQualificationRepository instituteQualificationRepository;

	@Override
	public List<InstituteQualification> findAll() {
		return instituteQualificationRepository.findAll();
	}

	@Override
	public InstituteQualification getByInstituteQualificationId(Long instituteQualificationId) {
		return instituteQualificationRepository.getByInstituteQualificationId(instituteQualificationId);
	}

	@Override
	public InstituteQualification save(InstituteQualification instituteQualification) {
		return instituteQualificationRepository.save(instituteQualification);
	}

//	@Override                               //One record from View
//	public VInstituteQualification getByVInstituteQualificationId(Long instituteQualificationId) {
//		return instituteQualificationRepository.getByVInstituteQualificationId(instituteQualificationId);
//	}


	@Override								//All in view
	public List<VInstituteQualification> findListAllInView() {
		return instituteQualificationRepository.findListAllInView();
	}

//	@Override								//List from View without parameter
//	public List<VInstituteQualification> findListInstituteQualificationXXX() {
//		return instituteQualificationRepository.findListVInstituteQualificationXXX();
//	}

	@Override								//List from View that needs parameter
	public List<VInstituteQualification> findListVInstituteQualificationForStudyInstitute(Long studyInstituteId) {
		return instituteQualificationRepository.findListVInstituteQualificationForStudyInstitute(studyInstituteId);
	}

//	@Override								//List from View that needs multiple parameters
//	public List<VInstituteQualification> findListInstituteQualificationXXX(Long paramId, String paramName, String paramName2) {
//		return instituteQualificationRepository.findListVInstituteQualificationXXX(paramId, paramName, paramName2);
//	}

//	@Override								//List from View that needs date parameters
//	public List<VInstituteQualification> findListInstituteQualificationXXX(Long paramId, Date fd, Date ld) {
//		return instituteQualificationRepository.findListVInstituteQualificationXXX(paramId, fd, ld);
//	}



	@Override
	public List<InstituteQualification> findListInstituteQualificationForStudyInstituteId(Long studyInstituteId) {
		return instituteQualificationRepository.findListInstituteQualificationForStudyInstituteId(studyInstituteId);
	}



}