package net.integrategroup.ignite.persistence.service;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import net.integrategroup.ignite.persistence.model.ProfessionalInstitute;
import net.integrategroup.ignite.persistence.repository.ProfessionalInstituteRepository;

/** @author Generated by Johannes Marais (JohannesSQL v7.7) **/
/** ******* ********* ** 2023-10-16 19:51:57 ******** ***** **/

@Service
public class ProfessionalInstituteServiceImpl implements ProfessionalInstituteService {

	@Autowired
	ProfessionalInstituteRepository professionalInstituteRepository;

	@Override
	public List<ProfessionalInstitute> findAll() {
		return professionalInstituteRepository.findAll();
	}

	@Override
	public ProfessionalInstitute getByProfessionalInstituteId(Long professionalInstituteId) {
		return professionalInstituteRepository.getByProfessionalInstituteId(professionalInstituteId);
	}

	@Override
	public ProfessionalInstitute save(ProfessionalInstitute professionalInstitute) {
		return professionalInstituteRepository.save(professionalInstitute);
	}

//	@Override                               //One record from View
//	public VProfessionalInstitute getByVProfessionalInstituteId(Long professionalInstituteId) {
//		return professionalInstituteRepository.getByVProfessionalInstituteId(professionalInstituteId);
//	}




}