package net.integrategroup.ignite.persistence.service;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import net.integrategroup.ignite.persistence.model.Province;
import net.integrategroup.ignite.persistence.model.VProvince;
import net.integrategroup.ignite.persistence.repository.ProvinceRepository;

/** @author Generated by Johannes Marais (JohannesSQL v7.7) **/
/** ******* ********* ** 2023-10-06 16:40:44 ******** ***** **/

@Service
public class ProvinceServiceImpl implements ProvinceService {

	@Autowired
	ProvinceRepository provinceRepository;

	@Override
	public List<Province> findAll() {
		return provinceRepository.findAll();
	}

	@Override
	public Province getByProvinceId(Long provinceId) {
		return provinceRepository.getByProvinceId(provinceId);
	}

	@Override
	public Province save(Province province) {
		return provinceRepository.save(province);
	}

//	@Override                               //One record from View
//	public VProvince getByVProvinceCode(Long provinceId) {
//		return provinceRepository.getByVProvinceCode(provinceCode);
//	}


	@Override								//All in view
	public List<VProvince> findListAllInView() {
		return provinceRepository.findListAllInView();
	}

//	@Override								//List from View without parameter
//	public List<VProvince> findListProvinceXXX() {
//		return provinceRepository.findListVProvinceXXX();
//	}

	@Override								//List from View that needs parameter
	public List<VProvince> findListVProvinceForCountry(Long countryId) {
		return provinceRepository.findListVProvinceForCountry(countryId);
	}

//	@Override								//List from View that needs multiple parameters
//	public List<VProvince> findListProvinceXXX(Long paramId, String paramName, String paramName2) {
//		return provinceRepository.findListVProvinceXXX(paramId, paramName, paramName2);
//	}

//	@Override								//List from View that needs date parameters
//	public List<VProvince> findListProvinceXXX(Long paramId, Date fd, Date ld) {
//		return provinceRepository.findListVProvinceXXX(paramId, fd, ld);
//	}



	@Override
	public List<VProvince> findListProvinceForCountryId(Long countryId) {
		return provinceRepository.findListProvinceForCountryId(countryId);
	}



}