package net.integrategroup.ignite.persistence.service;

import java.util.List;

import net.integrategroup.ignite.persistence.model.StudyInstitute;


/** @author Generated by Johannes Marais (JohannesSQL v7.7) **/
/** ******* ********* ** 2023-10-16 19:51:59 ******** ***** **/

public interface StudyInstituteService {

	List<StudyInstitute> findAll();

	StudyInstitute getByStudyInstituteId(Long studyInstituteId);            //retrieves one record, by PrimaryKey

	StudyInstitute save(StudyInstitute studyInstitute);


//	VStudyInstitute getByVStudyInstituteId(Long studyInstituteId);          //One record from View



}