package net.integrategroup.ignite.persistence.service;

import java.util.List;

import net.integrategroup.ignite.persistence.model.TypicalFolderStructure;
import net.integrategroup.ignite.persistence.model.VTfsTree;
import net.integrategroup.ignite.persistence.model.VTypicalFolderStructure;


/** @author Generated by Johannes Marais (JohannesSQL v7.7) **/
/** ******* ********* ** 2023-11-01 10:26:07 ******** ***** **/

public interface TypicalFolderStructureService {

	List<TypicalFolderStructure> findAll();

	TypicalFolderStructure getByTypicalFolderStructureId(Long typicalFolderStructureId);            //retrieves one record, by PrimaryKey

	TypicalFolderStructure save(TypicalFolderStructure typicalFolderStructure);


//	VTypicalFolderStructure getByVTypicalFolderStructureId(Long typicalFolderStructureId);          //One record from View

	List<VTfsTree> findListAllInTreeView();							//All in tree view

	List<VTfsTree> findListTopLevelInTreeView();					//Top Level in tree view
	
	List<VTypicalFolderStructure> findListAllInView();				//All in view

	
//	List<VTypicalFolderStructure> findListVTypicalFolderStructureXXX();										//List from View without parameter

//	List<VTypicalFolderStructure> findListVTypicalFolderStructureXXX(Long paramName);						//List from View that needs parameter

//	List<VTypicalFolderStructure> findListVTypicalFolderStructureXXX(Long paramId, String paramName, String paramName2);	//List from View that needs multiple parameters

//	List<VTypicalFolderStructure> findListVTypicalFolderStructureXXX(Long paramId, Date fd, Date ld);		//List from View that needs date parameters



	List<TypicalFolderStructure> findListTypicalFolderStructureForServiceDisciplineIdIndustry(Long serviceDisciplineId);

	List<TypicalFolderStructure> findListTypicalFolderStructureForTypicalFolderStructureIdParent(Long typicalFolderStructureId);



}