package net.integrategroup.ignite.controller.rest;

import java.sql.CallableStatement;
import java.util.List;
import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import net.integrategroup.ignite.persistence.model.StudyInstitute;
import net.integrategroup.ignite.persistence.service.DatabaseService;
import net.integrategroup.ignite.persistence.service.StudyInstituteService;
import net.integrategroup.ignite.utils.MapUtils;
import net.integrategroup.ignite.utils.SecurityUtils;



/** @author Generated by Johannes Marais (JohannesSQL v7.7) **/
/** ******* ********* ** 2023-10-16 19:51:59 ******** ***** **/


@RestController
@RequestMapping("/rest/ignite/v1/study-institute")

public class StudyInstituteController {

	@Autowired
	StudyInstituteService studyInstituteService;

	@Autowired
	SecurityUtils securityUtils;

	@Autowired
	DatabaseService databaseService;

	@GetMapping("/find-all")          //All records in the StudyInstitute Table
	public ResponseEntity<?> findAll() {
		try {
			List<StudyInstitute> result = studyInstituteService.findAll();
			return ResponseEntity.ok(result);
		} catch (Exception e) {
			return ResponseEntity.badRequest().body(e.getMessage());
		}
	}

	@GetMapping("/by-study-institute-id/{studyInstituteId}")   //Find the record by the PrimaryKey
	public ResponseEntity<?> getByStudyInstituteId(@PathVariable("studyInstituteId") Long studyInstituteId) {
		try {
			StudyInstitute result = studyInstituteService.getByStudyInstituteId(studyInstituteId);
			return ResponseEntity.ok(result);
		} catch (Exception e) {
			return ResponseEntity.badRequest().body(e.getMessage());
		}
	}

	@PostMapping()       //Save (update)
	public ResponseEntity<?> saveStudyInstitute(@RequestBody StudyInstitute studyInstitute) {
		try {
			StudyInstitute test = studyInstituteService.getByStudyInstituteId(studyInstitute.getStudyInstituteId());
			if (test == null) {
				throw new Exception("StudyInstitute not found");
			}
			studyInstitute = studyInstituteService.save(studyInstitute);
			return ResponseEntity.ok(studyInstitute);
		} catch (Exception e) {
			return ResponseEntity.badRequest().body(e.getMessage());
		}
	}

	@PostMapping("/new")   //Save (new)
	public ResponseEntity<?> saveStudyInstituteNew(@RequestBody StudyInstitute studyInstitute) {
		try {
			StudyInstitute test = studyInstituteService.getByStudyInstituteId(studyInstitute.getStudyInstituteId());
			if (test != null) {
				throw new Exception("The StudyInstitute already exists");
			}
			studyInstitute = studyInstituteService.save(studyInstitute);
			return ResponseEntity.ok(studyInstitute);
		} catch (Exception e) {
			return ResponseEntity.badRequest().body(e.getMessage());
		}
	}

//	@GetMapping("/by-view-study-institute-id/{studyInstituteId}")   //One record from View
//	public ResponseEntity<?> getByVStudyInstituteId(@PathVariable("studyInstituteId") Long studyInstituteId) {
//		try {
//			VStudyInstitute result = studyInstituteService.getByVStudyInstituteId(studyInstituteId);
//			return ResponseEntity.ok(result);
//		} catch (Exception e) {
//			return ResponseEntity.badRequest().body(e.getMessage());
//		}
//	}


	@PostMapping("/delete")   //Delete a record, and insert into AuditTrial table
	public ResponseEntity<?> deleteStudyInstitute(@RequestBody Map<String, Object> data) {

		MapUtils mu = new MapUtils();

		Long studyInstituteId = mu.getAsLongOrNull(data, "studyInstituteId");
		String sql = "CALL ig_db.deleteStudyInstitute(?, ?);";

		String exampleSql = "CALL ig_db.deleteStudyInstitute(" + studyInstituteId + ", '"
			+ securityUtils.getUsername() + "');";
		System.out.println("\n\n\n" + exampleSql + "\n\n\n"); // Prints out, but does not execute, for debugging

		try {	//**//					
			Object[] params = {		
				studyInstituteId	
			};						
			
			databaseService.executeStoredProc(sql, params);
			return ResponseEntity.ok().build();
			//**//
		} catch (Exception e) {
			e.printStackTrace();
			return ResponseEntity.badRequest().body(e.getMessage());
		}
	}



}